// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "../../../../BaseClient.js";
import * as core from "../../../../core/index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Hedra from "../../../index.js";

export declare namespace ModelsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {
    }
}

/**
 * Discover models and estimate cost.
 */
export class ModelsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ModelsClient.Options>;

    constructor(options: ModelsClient.Options = {}) {

        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {Hedra.ModelsListRequest} request
     * @param {ModelsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Hedra.BadRequestError}
     * @throws {@link Hedra.ForbiddenError}
     * @throws {@link Hedra.NotFoundError}
     * @throws {@link Hedra.TooManyRequestsError}
     * @throws {@link Hedra.InternalServerError}
     * @throws {@link errors.HedraError}
     * @throws {@link errors.HedraTimeoutError}
     *
     * @example
     *     await client.models.list()
     */
    public list(request: Hedra.ModelsListRequest = {}, requestOptions?: ModelsClient.RequestOptions): core.HttpResponsePromise<Hedra.ModelListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(request: Hedra.ModelsListRequest = {}, requestOptions?: ModelsClient.RequestOptions): Promise<core.WithRawResponse<Hedra.ModelListResponse>> {
        const { modality } = request;
        const _queryParams: Record<string, unknown> = {
            modality: modality !== undefined ? modality : undefined
        };
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, mergeOnlyDefinedHeaders({ "X-Hedra-Spec-Version": requestOptions?.specVersion ?? "3.0.0" }), requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(await core.Supplier.get(this._options.baseUrl) ?? (await core.Supplier.get(this._options.environment) ?? environments.HedraEnvironment.Production), "models"),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().addMany(_queryParams).mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging
        });
        if (_response.ok) {
            return { data: _response.body as Hedra.ModelListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400: throw new Hedra.BadRequestError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 403: throw new Hedra.ForbiddenError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 404: throw new Hedra.NotFoundError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 429: throw new Hedra.TooManyRequestsError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 500: throw new Hedra.InternalServerError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                default: throw new errors.HedraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.body,
                    rawResponse: _response.rawResponse
                });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/models");
    }

    /**
     * @param {string} model - The model's public id (`GET /v3/models`).
     * @param {Hedra.ModelsGetRequest} request
     * @param {ModelsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Hedra.BadRequestError}
     * @throws {@link Hedra.ForbiddenError}
     * @throws {@link Hedra.NotFoundError}
     * @throws {@link Hedra.TooManyRequestsError}
     * @throws {@link Hedra.InternalServerError}
     * @throws {@link errors.HedraError}
     * @throws {@link errors.HedraTimeoutError}
     *
     * @example
     *     await client.models.get("model")
     */
    public get(model: string, request: Hedra.ModelsGetRequest = {}, requestOptions?: ModelsClient.RequestOptions): core.HttpResponsePromise<Hedra.ModelDetail> {
        return core.HttpResponsePromise.fromPromise(this.__get(model, request, requestOptions));
    }

    private async __get(model: string, request: Hedra.ModelsGetRequest = {}, requestOptions?: ModelsClient.RequestOptions): Promise<core.WithRawResponse<Hedra.ModelDetail>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, mergeOnlyDefinedHeaders({ "X-Hedra-Spec-Version": requestOptions?.specVersion ?? "3.0.0" }), requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(await core.Supplier.get(this._options.baseUrl) ?? (await core.Supplier.get(this._options.environment) ?? environments.HedraEnvironment.Production), `models/${core.url.encodePathParam(model)}`),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging
        });
        if (_response.ok) {
            return { data: _response.body as Hedra.ModelDetail, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400: throw new Hedra.BadRequestError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 403: throw new Hedra.ForbiddenError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 404: throw new Hedra.NotFoundError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 429: throw new Hedra.TooManyRequestsError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 500: throw new Hedra.InternalServerError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                default: throw new errors.HedraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.body,
                    rawResponse: _response.rawResponse
                });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/models/{model}");
    }

    /**
     * @param {string} model - The model's public id (`GET /v3/models`).
     * @param {Hedra.ModelsListModelJobsRequest} request
     * @param {ModelsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Hedra.BadRequestError}
     * @throws {@link Hedra.UnauthorizedError}
     * @throws {@link Hedra.ForbiddenError}
     * @throws {@link Hedra.NotFoundError}
     * @throws {@link Hedra.TooManyRequestsError}
     * @throws {@link Hedra.InternalServerError}
     * @throws {@link errors.HedraError}
     * @throws {@link errors.HedraTimeoutError}
     *
     * @example
     *     await client.models.listModelJobs("model")
     */
    public async listModelJobs(model: string, request: Hedra.ModelsListModelJobsRequest = {}, requestOptions?: ModelsClient.RequestOptions): Promise<core.Page<Hedra.JobSummary, Hedra.JobListResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(async (request: Hedra.ModelsListModelJobsRequest): Promise<core.WithRawResponse<Hedra.JobListResponse>> => { const { limit, cursor } = request; const _queryParams: Record<string, unknown> = {
            limit,
            cursor
        }; const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest(); let _headers: core.Fetcher.Args["headers"] = mergeHeaders(_authRequest.headers, this._options?.headers, mergeOnlyDefinedHeaders({ "X-Hedra-Spec-Version": requestOptions?.specVersion ?? "3.0.0" }), requestOptions?.headers); const _response = await core.fetcher({
            url: core.url.join(await core.Supplier.get(this._options.baseUrl) ?? (await core.Supplier.get(this._options.environment) ?? environments.HedraEnvironment.Production), `models/${core.url.encodePathParam(model)}/jobs`),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().addMany(_queryParams).mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging
        }); if (_response.ok) {
            return { data: _response.body as Hedra.JobListResponse, rawResponse: _response.rawResponse };
        } if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400: throw new Hedra.BadRequestError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 401: throw new Hedra.UnauthorizedError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 403: throw new Hedra.ForbiddenError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 404: throw new Hedra.NotFoundError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 429: throw new Hedra.TooManyRequestsError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 500: throw new Hedra.InternalServerError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                default: throw new errors.HedraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.body,
                    rawResponse: _response.rawResponse
                });
            }
        } return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/models/{model}/jobs"); });
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<Hedra.JobSummary, Hedra.JobListResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: response => response?.next_cursor != null && !(typeof response?.next_cursor === "string" && response?.next_cursor === ""),
            getItems: response => response?.data ?? [],
            loadPage: response => { return list(core.setObjectProperty(request, "cursor", response?.next_cursor)); }
        });
    }

    /**
     * Voices this model accepts — scoped to the model's voice provider.
     *
     * @param {string} model - The model's public id (`GET /v3/models`).
     * @param {Hedra.ModelsListVoicesRequest} request
     * @param {ModelsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Hedra.BadRequestError}
     * @throws {@link Hedra.ForbiddenError}
     * @throws {@link Hedra.NotFoundError}
     * @throws {@link Hedra.TooManyRequestsError}
     * @throws {@link Hedra.InternalServerError}
     * @throws {@link errors.HedraError}
     * @throws {@link errors.HedraTimeoutError}
     *
     * @example
     *     await client.models.listVoices("model")
     */
    public listVoices(model: string, request: Hedra.ModelsListVoicesRequest = {}, requestOptions?: ModelsClient.RequestOptions): core.HttpResponsePromise<Hedra.VoiceListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listVoices(model, request, requestOptions));
    }

    private async __listVoices(model: string, request: Hedra.ModelsListVoicesRequest = {}, requestOptions?: ModelsClient.RequestOptions): Promise<core.WithRawResponse<Hedra.VoiceListResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, mergeOnlyDefinedHeaders({ "X-Hedra-Spec-Version": requestOptions?.specVersion ?? "3.0.0" }), requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(await core.Supplier.get(this._options.baseUrl) ?? (await core.Supplier.get(this._options.environment) ?? environments.HedraEnvironment.Production), `models/${core.url.encodePathParam(model)}/voices`),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging
        });
        if (_response.ok) {
            return { data: _response.body as Hedra.VoiceListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400: throw new Hedra.BadRequestError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 403: throw new Hedra.ForbiddenError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 404: throw new Hedra.NotFoundError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 429: throw new Hedra.TooManyRequestsError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 500: throw new Hedra.InternalServerError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                default: throw new errors.HedraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.body,
                    rawResponse: _response.rawResponse
                });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/models/{model}/voices");
    }

    /**
     * A standalone one-operation OpenAPI spec for this model's submit call.
     *
     * @param {string} model - The model's public id (`GET /v3/models`).
     * @param {Hedra.ModelsGetOpenapiRequest} request
     * @param {ModelsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Hedra.BadRequestError}
     * @throws {@link Hedra.ForbiddenError}
     * @throws {@link Hedra.NotFoundError}
     * @throws {@link Hedra.TooManyRequestsError}
     * @throws {@link Hedra.InternalServerError}
     * @throws {@link errors.HedraError}
     * @throws {@link errors.HedraTimeoutError}
     *
     * @example
     *     await client.models.getOpenapi("model")
     */
    public getOpenapi(model: string, request: Hedra.ModelsGetOpenapiRequest = {}, requestOptions?: ModelsClient.RequestOptions): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__getOpenapi(model, request, requestOptions));
    }

    private async __getOpenapi(model: string, request: Hedra.ModelsGetOpenapiRequest = {}, requestOptions?: ModelsClient.RequestOptions): Promise<core.WithRawResponse<Record<string, unknown>>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, mergeOnlyDefinedHeaders({ "X-Hedra-Spec-Version": requestOptions?.specVersion ?? "3.0.0" }), requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(await core.Supplier.get(this._options.baseUrl) ?? (await core.Supplier.get(this._options.environment) ?? environments.HedraEnvironment.Production), `models/${core.url.encodePathParam(model)}/openapi.json`),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400: throw new Hedra.BadRequestError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 403: throw new Hedra.ForbiddenError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 404: throw new Hedra.NotFoundError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 429: throw new Hedra.TooManyRequestsError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 500: throw new Hedra.InternalServerError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                default: throw new errors.HedraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.body,
                    rawResponse: _response.rawResponse
                });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/models/{model}/openapi.json");
    }

    /**
     * @param {string} model - The model's public id (`GET /v3/models`).
     * @param {Hedra.EstimateRequest} request
     * @param {ModelsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Hedra.BadRequestError}
     * @throws {@link Hedra.UnauthorizedError}
     * @throws {@link Hedra.ForbiddenError}
     * @throws {@link Hedra.NotFoundError}
     * @throws {@link Hedra.TooManyRequestsError}
     * @throws {@link Hedra.InternalServerError}
     * @throws {@link errors.HedraError}
     * @throws {@link errors.HedraTimeoutError}
     *
     * @example
     *     await client.models.estimate("model")
     */
    public estimate(model: string, request: Hedra.EstimateRequest = {}, requestOptions?: ModelsClient.RequestOptions): core.HttpResponsePromise<Hedra.EstimateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__estimate(model, request, requestOptions));
    }

    private async __estimate(model: string, request: Hedra.EstimateRequest = {}, requestOptions?: ModelsClient.RequestOptions): Promise<core.WithRawResponse<Hedra.EstimateResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(_authRequest.headers, this._options?.headers, mergeOnlyDefinedHeaders({ "X-Hedra-Spec-Version": requestOptions?.specVersion ?? "3.0.0" }), requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(await core.Supplier.get(this._options.baseUrl) ?? (await core.Supplier.get(this._options.environment) ?? environments.HedraEnvironment.Production), `models/${core.url.encodePathParam(model)}/estimate`),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging
        });
        if (_response.ok) {
            return { data: _response.body as Hedra.EstimateResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400: throw new Hedra.BadRequestError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 401: throw new Hedra.UnauthorizedError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 403: throw new Hedra.ForbiddenError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 404: throw new Hedra.NotFoundError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 429: throw new Hedra.TooManyRequestsError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 500: throw new Hedra.InternalServerError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                default: throw new errors.HedraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.body,
                    rawResponse: _response.rawResponse
                });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/models/{model}/estimate");
    }
}
