// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Hedra from "../../../index.js";

export declare namespace TokensClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class TokensClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<TokensClient.Options>;

    constructor(options: TokensClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {Hedra.TokenCreateRequest} request
     * @param {TokensClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Hedra.BadRequestError}
     * @throws {@link Hedra.UnauthorizedError}
     * @throws {@link Hedra.ForbiddenError}
     * @throws {@link Hedra.NotFoundError}
     * @throws {@link Hedra.TooManyRequestsError}
     * @throws {@link Hedra.InternalServerError}
     * @throws {@link errors.HedraError}
     * @throws {@link errors.HedraTimeoutError}
     *
     * @example
     *     await client.tokens.create()
     */
    public create(
        request: Hedra.TokenCreateRequest = {},
        requestOptions?: TokensClient.RequestOptions,
    ): core.HttpResponsePromise<Hedra.TokenCreateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: Hedra.TokenCreateRequest = {},
        requestOptions?: TokensClient.RequestOptions,
    ): Promise<core.WithRawResponse<Hedra.TokenCreateResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Hedra-Spec-Version": requestOptions?.specVersion ?? "3.9.0" }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.HedraEnvironment.Production,
                "tokens",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Hedra.TokenCreateResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Hedra.BadRequestError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 401:
                    throw new Hedra.UnauthorizedError(
                        _response.error.body as Hedra.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Hedra.ForbiddenError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 404:
                    throw new Hedra.NotFoundError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Hedra.TooManyRequestsError(
                        _response.error.body as Hedra.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Hedra.InternalServerError(
                        _response.error.body as Hedra.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.HedraError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/tokens");
    }
}
