// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         url: "url"
 *     }
 */
export interface WebhookDefaultUpdate {
    /** HTTPS endpoint to receive terminal webhooks for every job that names no per-job `webhook` on submit. */
    url: string;
    /** Whether the default endpoint receives deliveries; false pauses it without discarding the URL. */
    enabled?: boolean;
}
