// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../../../../index.js";

/**
 * @example
 *     {
 *         input: {
 *             source_video: {
 *                 source: "url",
 *                 url: "url"
 *             },
 *             resolution: "1080p"
 *         }
 *     }
 */
export interface SubmitBodyTopazVideoUpscalerStarlightPrecise {
    input: Hedra.InputTopazVideoUpscalerStarlightPrecise;
    /** URL to receive a signed completion webhook. */
    webhook?: string | null;
}
