// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../../../../index.js";

/**
 * @example
 *     {
 *         input: {
 *             prompt: "prompt",
 *             resolution: "360p",
 *             duration_ms: 1,
 *             quality: "standard"
 *         }
 *     }
 */
export interface SubmitBodyViduQ3 {
    input: Hedra.InputViduQ3;
    /** URL to receive a signed completion webhook. */
    webhook?: string | null;
    /** Replays the original ack for a retried submit instead of enqueueing a duplicate job. */
    idempotency_key?: string | null;
}
