// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../../../../index.js";

/**
 * @example
 *     {
 *         input: {
 *             prompt: "prompt",
 *             aspect_ratio: "4:1",
 *             images: [{
 *                     source: "url",
 *                     url: "url"
 *                 }]
 *         }
 *     }
 */
export interface SubmitBodyReve21Remix {
    input: Hedra.InputReve21Remix;
    /** URL to receive a signed completion webhook. */
    webhook?: string | null;
    /** Replays the original ack for a retried submit instead of enqueueing a duplicate job. */
    idempotency_key?: string | null;
}
