// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../../../../index.js";

/**
 * @example
 *     {
 *         input: {
 *             prompt: "prompt",
 *             resolution: "480p",
 *             duration_ms: 1,
 *             start_image: {
 *                 source: "url",
 *                 url: "url"
 *             },
 *             camera_trajectory: [{
 *                     time: 1.1,
 *                     azimuth: 1.1,
 *                     elevation: 1.1,
 *                     distance: 1.1
 *                 }]
 *         }
 *     }
 */
export interface SubmitBodyMinimaxH3MaxCameraControls {
    input: Hedra.InputMinimaxH3MaxCameraControls;
    /** URL to receive a signed completion webhook. */
    webhook?: string | null;
    /** Replays the original ack for a retried submit instead of enqueueing a duplicate job. */
    idempotency_key?: string | null;
}
