// This file was auto-generated by Fern from our API Definition.

import * as Hedra from "../../../../index.js";

/**
 * @example
 *     {
 *         input: {
 *             prompt: "prompt",
 *             resolution: "720p",
 *             duration_ms: 1
 *         }
 *     }
 */
export interface SubmitBodyWan27 {
    input: Hedra.InputWan27;
    /** URL to receive a signed completion webhook. */
    webhook?: string | null;
    /** Replays the original ack for a retried submit instead of enqueueing a duplicate job. */
    idempotency_key?: string | null;
}
