// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../../../../index.js";

/**
 * @example
 *     {
 *         input: {
 *             text: "text",
 *             duration_ms: 1
 *         }
 *     }
 */
export interface SubmitBodyElevenlabsSoundEffects {
    input: Hedra.InputElevenlabsSoundEffects;
    /** URL to receive a signed completion webhook. */
    webhook?: string | null;
}
