// This file was auto-generated by Fern from our API Definition.

import * as Hedra from "../../../../index.js";

/**
 * @example
 *     {
 *         input: {
 *             prompt: "prompt",
 *             aspect_ratio: "1:1",
 *             resolution: "480p",
 *             duration_ms: 1
 *         }
 *     }
 */
export interface SubmitBodySeedance20Mini {
    input: Hedra.InputSeedance20Mini;
    /** URL to receive a signed completion webhook. */
    webhook?: string | null;
    /** Replays the original ack for a retried submit instead of enqueueing a duplicate job. */
    idempotency_key?: string | null;
}
