// This file was auto-generated by Fern from our API Definition.

import * as Hedra from "../../../../index.js";

/**
 * @example
 *     {
 *         input: {
 *             prompt: "prompt",
 *             aspect_ratio: "16:9",
 *             resolution: "1K",
 *             quality: "low"
 *         }
 *     }
 */
export interface SubmitBodyGptImage2 {
    input: Hedra.InputGptImage2;
    /** URL to receive a signed completion webhook. */
    webhook?: string | null;
    /** Replays the original ack for a retried submit instead of enqueueing a duplicate job. */
    idempotency_key?: string | null;
}
