// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../../../../index.js";

/**
 * @example
 *     {
 *         input: {
 *             aspect_ratio: "16:9",
 *             duration_ms: 1
 *         }
 *     }
 */
export interface SubmitBodyKlingV3 {
    input: Hedra.InputKlingV3;
    /** URL to receive a signed completion webhook. */
    webhook?: string | null;
    /** Replays the original ack for a retried submit instead of enqueueing a duplicate job. */
    idempotency_key?: string | null;
}
