// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../../../../index.js";

/**
 * @example
 *     {
 *         input: {
 *             audio: {
 *                 source: "url",
 *                 url: "url"
 *             }
 *         }
 *     }
 */
export interface SubmitBodyElevenlabsAudioIsolation {
    input: Hedra.InputElevenlabsAudioIsolation;
    /** URL to receive a signed completion webhook. */
    webhook?: string | null;
}
