// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../core/index.js";
import * as errors from "../../errors/index.js";
import type * as Hedra from "../index.js";

export class ServiceUnavailableError extends errors.HedraError {
    public declare readonly body: Hedra.OpenAiErrorResponse;

    constructor(body: Hedra.OpenAiErrorResponse, rawResponse?: core.RawResponse) {
        super({
            message: "ServiceUnavailableError",
            statusCode: 503,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }

        this.name = "ServiceUnavailableError";
    }
}
