// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface BillingGetUsageRequest {
    start?: string | null;
    end?: string | null;
    group_by?: Hedra.UsageGroupBy;
}
