// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface BillingListLlmUsageRequest {
    /** Maximum items per page. */
    limit?: number;
    /** Opaque cursor from the previous page's `next_cursor`; omit for the first page. Each cursor records the filters it was issued under, so a walk must keep them fixed. */
    cursor?: string | null;
    /** Only requests created at or after this instant (ISO-8601). Unlike `GET /v3/usage` there is no default window and no window cap. */
    start?: string | null;
    /** Only requests created before this instant (ISO-8601, exclusive). */
    end?: string | null;
    /** Only requests admitted for this model id. */
    model?: string | null;
    /** Only requests made with this API key (its `key_id`, as listed by GET /v3/keys). An unknown key id yields an empty page. */
    key_id?: string | null;
}
