// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface EstimateRequest {
    /** The same model-specific inputs a submit would carry; the estimate prices exactly this body. */
    input?: Record<string, unknown>;
}
