// This file was auto-generated by Fern from our API Definition.

export const WebhookBillingTopOffFailedPayloadXHedraWebhookRedelivery = {
    True: "true",
    False: "false",
} as const;
export type WebhookBillingTopOffFailedPayloadXHedraWebhookRedelivery =
    (typeof WebhookBillingTopOffFailedPayloadXHedraWebhookRedelivery)[keyof typeof WebhookBillingTopOffFailedPayloadXHedraWebhookRedelivery];
