// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

export interface AiModel {
    /** ID of the model */
    id: string;
    /** Name of the model */
    name: string;
    /** Description of the model. */
    description: string | null;
    /** Type of generation the model applies to. */
    type: string;
    /** Aspect ratios the model supports. */
    aspect_ratios?: (string[] | null) | undefined;
    /** Resolutions the model supports. */
    resolutions?: (string[] | null) | undefined;
    /** Durations the model supports. */
    durations?: (string[] | null) | undefined;
    /** Whether the model is conditioned by a start frame. */
    requires_start_frame?: (boolean | null) | undefined;
    /** Whether the model is conditioned by an end frame. */
    requires_end_frame?: (boolean | null) | undefined;
    /** Whether the model is conditioned by audio input. */
    requires_audio_input?: (boolean | null) | undefined;
    /** Whether the model requires video input (video-to-video). */
    requires_input_video?: (boolean | null) | undefined;
    /** Whether the model requires character orientation (motion control). */
    requires_character_orientation?: (boolean | null) | undefined;
    /** Maximum video duration in milliseconds. Only applies to audio-driven models. */
    max_duration_ms?: (number | null) | undefined;
    /** Whether the model supports custom resolution. */
    custom_resolution?: (boolean | null) | undefined;
    /** Pricing details of the model. */
    price_details: Hedra.AiModelPrice;
    /** Extensible pricing information with dimension modifiers for resolution, audio, etc. */
    pricing?: (Hedra.Pricing | null) | undefined;
    /** Width and height for each aspect_ratio and resolution tuple. */
    dimensions?: (Record<string, Record<string, Hedra.Dimension | null> | null> | null) | undefined;
    /** URL of the model's logo in SVG format. */
    logo_url?: (string | null) | undefined;
    /** Whether this is a premium model. */
    premium?: boolean | undefined;
    /** Display order for UI sorting. Lower values appear first. */
    display_order?: (number | null) | undefined;
}
