// This file was auto-generated by Fern from our API Definition.

/**
 * Least-privilege grants carried by v3 API keys.
 *
 * Stored as text[] on api_keys; NULL scopes means full access (legacy keys).
 * Scopes are stored as text so new least-privilege surfaces can be introduced
 * without a database-enum migration.
 */
export const ApiKeyScope = {
        JobsRead: "jobs:read",
        JobsWrite: "jobs:write",
        ModelsRead: "models:read",
        FilesWrite: "files:write",
        WebhooksManage: "webhooks:manage",
        LogDrainsManage: "log_drains:manage",
        UsageRead: "usage:read",
        KeysManage: "keys:manage"
    } as const;
export type ApiKeyScope = typeof ApiKeyScope[keyof typeof ApiKeyScope];
