// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Individual result item in a batch video generation.
 */
export interface BatchVideoResultItem {
    /** The id of the generation created. None if failed. */
    id?: (string | null) | undefined;
    /** The id of the video asset resulting from the generation. None if failed. */
    asset_id?: (string | null) | undefined;
    /** Date the generation was submitted. */
    created_at: string;
    /** Status of the generation */
    status: Hedra.GenerationStatus;
    /** Current progress to completion. Between 0-1 */
    progress: number;
    /** Error message if this item failed. */
    error?: (string | null) | undefined;
}
