// This file was auto-generated by Fern from our API Definition.

export interface ChatTokenPricing {
    /** USD per million prompt tokens, cached tokens included. */
    usd_per_1m_input_tokens: number;
    /** USD per million completion tokens, reasoning tokens included. */
    usd_per_1m_output_tokens: number;
}
