// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Top-level error body: ``{"error": {...}}`` plus a debug id.
 */
export interface ErrorResponse {
    error: Hedra.ErrorEnvelope;
    /** Debug id to quote to support (32-char hex trace id), also emitted as the `X-Trace-Id` response header. */
    trace_id?: (string | null) | undefined;
}
