// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Top-level error body: ``{"error": {...}}``.
 */
export interface ErrorResponse {
    error: Hedra.ErrorEnvelope;
}
