// This file was auto-generated by Fern from our API Definition.

/**
 * The OpenAI error type for an error's HTTP status, published so an
 * OpenAI SDK's `APIStatusError.type` carries a value.
 */
export const ErrorType = {
    InvalidRequestError: "invalid_request_error",
    AuthenticationError: "authentication_error",
    PermissionError: "permission_error",
    RateLimitError: "rate_limit_error",
    ServerError: "server_error",
} as const;
export type ErrorType = (typeof ErrorType)[keyof typeof ErrorType];
