// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

export interface ErrorEnvelope {
    code: Hedra.ErrorCode;
    message: string;
    retryable?: boolean | undefined;
    retry_after?: (number | null) | undefined;
}
