// This file was auto-generated by Fern from our API Definition.

/**
 * The price, in US dollars, of submitting the request's `input` to the model.
 */
export interface EstimateResponse {
    /** The resolved model id this estimate prices. */
    model: string;
    /** The price of submitting the request's `input` to the model, in `currency`. */
    cost: number;
    /** ISO-4217 currency code for `cost`. */
    currency: string;
}
