// This file was auto-generated by Fern from our API Definition.

/**
 * Price of a would-be submit, in US dollars.
 */
export interface EstimateResponse {
    /** The resolved model id this estimate prices. */
    model: string;
    /** Price of a would-be submit. */
    cost: number;
    /** ISO-4217 currency code for `cost`. */
    currency: string;
}
