// This file was auto-generated by Fern from our API Definition.

/**
 * One field-level validation problem in a request body.
 *
 * `field` is the dotted path to the offending input (e.g. `input.resolution`);
 * `allowed` lists the accepted values when the field is an enum, so a caller
 * can fix it without re-fetching the model schema.
 */
export interface FieldError {
    field: string;
    message: string;
    reason?: (string | null) | undefined;
    allowed?: (string[] | null) | undefined;
}
