// This file was auto-generated by Fern from our API Definition.

/**
 * Generation type enum
 *
 * NOTE: this enum is used to determine the type of generation and is used to determine
 * the type of asset that will be generated.
 */
export const GenerationType = {
    Image: "image",
    Video: "video",
    TextToSpeech: "text_to_speech",
    SpeechToSpeech: "speech_to_speech",
    VoiceClone: "voice_clone",
    AudioIsolation: "audio_isolation",
    VideoStitching: "video_stitching",
    VideoUpscale: "video_upscale",
    VideoToVideo: "video_to_video",
    ImageUpscale: "image_upscale",
    AgentResponse: "agent_response",
    AudioFromVideo: "audio_from_video",
    TextToSound: "text_to_sound",
    AssetsToImageTextPrompt: "assets_to_image_text_prompt",
    AssetsToAudioTextPrompt: "assets_to_audio_text_prompt",
} as const;
export type GenerationType = (typeof GenerationType)[keyof typeof GenerationType];
