// This file was auto-generated by Fern from our API Definition.

/**
 * Audio generation request that extracts sound effects from video using Mirelo Studio.
 */
export interface GenerateAudioFromVideoRequest {
    workspace_id?: (string | null) | undefined;
    /** Optional agent thread ID to associate this generation with. */
    agent_thread_id?: (string | null) | undefined;
    /** Optional pre-reserved generation ID. If provided, this ID will be used instead of generating a new one. For batch operations (batch_size > 1), use generation_ids instead. */
    generation_id?: (string | null) | undefined;
    /** Optional list of pre-reserved generation IDs for batch operations. Length must match batch_size. Mutually exclusive with generation_id. */
    generation_ids?: (string[] | null) | undefined;
    /** ID of the model to use for video-to-audio generation (Mirelo Studio). */
    audio_generation_model_id: string;
    /** The id of the video asset to generate audio from. */
    video_id: string;
    /** Optional prompt to guide the audio generation. */
    prompt?: (string | null) | undefined;
}
