// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

export interface GeneratedVideoInputs {
    /** Prompt for video generation. */
    text_prompt: string;
    /** The id of the model used for generation. */
    ai_model_id?: (string | null) | undefined;
    /** Resolution for the video. */
    resolution?: (string | null) | undefined;
    /** Aspect ratio for the video. */
    aspect_ratio?: (string | null) | undefined;
    /** Duration of the video in milliseconds. */
    duration_ms?: (number | null) | undefined;
    /** Normalized coordinates for primary speaker position (Character3 only) */
    bounding_box_target?: (Hedra.NormalizedPoint | null) | undefined;
    /** For motion control models: 'video' matches reference video orientation (better for complex motions, max 30s), 'image' preserves character image orientation (better for camera movements, max 10s). */
    character_orientation?: (GeneratedVideoInputs.CharacterOrientation | null) | undefined;
    /** If true, automatically enhance the prompt before generation. */
    enhance_prompt?: boolean | undefined;
}

export namespace GeneratedVideoInputs {
    export const CharacterOrientation = {
        Video: "video",
        Image: "image",
    } as const;
    export type CharacterOrientation = (typeof CharacterOrientation)[keyof typeof CharacterOrientation];
}
