// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

export interface GenerationStatusResponse {
    /** ID of the generation. */
    id: string;
    /** ID of the generated asset. */
    asset_id: string;
    /** Type of generation. */
    type: Hedra.AssetType;
    /** Status of the generation. */
    status: Hedra.GenerationStatus;
    /** Current progress to completion. Between 0-1 */
    progress: number;
    /** Date the generation was submitted. */
    created_at: string;
    /** Error message. Value is not present unless the status of the generation is 'error' */
    error_message?: (string | null) | undefined;
    /** URL of the generated asset. */
    url?: (string | null) | undefined;
    /** URL to download the asset. */
    download_url?: (string | null) | undefined;
    /** URL to stream the asset. */
    streaming_url?: (string | null) | undefined;
    /** ID of the workspace this generation belongs to. */
    workspace_id?: (string | null) | undefined;
}
