// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Motion Control request for transferring motion from a reference video to a character image.
 * Processed through V2V infrastructure internally.
 */
export interface GenerateMotionControlRequestInput {
    workspace_id?: (string | null) | undefined;
    /** Optional agent thread ID to associate this generation with. */
    agent_thread_id?: (string | null) | undefined;
    /** Optional pre-reserved generation ID. If provided, this ID will be used instead of generating a new one. For batch operations (batch_size > 1), use generation_ids instead. */
    generation_id?: (string | null) | undefined;
    /** Optional list of pre-reserved generation IDs for batch operations. Length must match batch_size. Mutually exclusive with generation_id. */
    generation_ids?: (string[] | null) | undefined;
    /** The id of the Motion Control model to use. */
    ai_model_id: string;
    /** The id of the video asset to use as motion reference. */
    video_id: string;
    /** The id of the character image asset to animate with the motion from the video. */
    start_keyframe_id: string;
    /** Video generation parameters including text_prompt and character_orientation. */
    generated_video_inputs: Hedra.GeneratedVideoInputs;
}
