// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

export interface GenerateVideoResponse {
    workspace_id?: (string | null) | undefined;
    /** Optional agent thread ID to associate this generation with. */
    agent_thread_id?: (string | null) | undefined;
    /** Optional pre-reserved generation ID. If provided, this ID will be used instead of generating a new one. For batch operations (batch_size > 1), use generation_ids instead. */
    generation_id?: (string | null) | undefined;
    /** Optional list of pre-reserved generation IDs for batch operations. Length must match batch_size. Mutually exclusive with generation_id. */
    generation_ids?: (string[] | null) | undefined;
    /** ID of the model to use for the generation. */
    ai_model_id?: string | undefined;
    /** The id of the Image asset to use as the start keyframe. This will be ignored if reference_image_ids is provided. */
    start_keyframe_id?: (string | null) | undefined;
    /** The URL of the image to use as the start keyframe. */
    start_keyframe_url?: (string | null) | undefined;
    /** The id of the Image asset to use as the end keyframe. This will be ignored if reference_image_ids is provided. */
    end_keyframe_id?: (string | null) | undefined;
    /** The URL of the image to use as the end keyframe. */
    end_keyframe_url?: (string | null) | undefined;
    /** The id of the Audio asset to use. */
    audio_id?: (string | null) | undefined;
    /** Optional TTS parameters for server-side audio generation. If provided (and audio_id is not), audio will be generated from these params before video generation. */
    audio_generation?: (Hedra.GenerateTextToSpeechRequest | null) | undefined;
    /** Audio start offset in milliseconds. Negative values prepend silence (e.g., -1000 adds 1s silence before audio). Positive values crop from the beginning of the source audio (e.g., 2000 skips the first 2s). Use with generated_video_inputs.duration_ms to control total output length. */
    audio_start_ms?: (number | null) | undefined;
    /** The id(s) of the image(s) to reference in the generation. Only used for multi-image video generation and will supersede start_keyframe_id. */
    reference_image_ids?: (string[] | null) | undefined;
    /** The id of the Video asset to use as motion input for V2V (motion control) models. */
    video_id?: (string | null) | undefined;
    /** Inputs for generating the video. */
    generated_video_inputs: Hedra.GeneratedVideoInputs;
    /** Number of video variations to generate (1-8). When > 1, batch_results will contain all generation results. */
    batch_size?: number | undefined;
    /** The id of the generation created. */
    id: string;
    /** The id of the video asset resulting from the generation. */
    asset_id: string;
    /** Date the generation was submitted. */
    created_at: string;
    /** Status of the generation */
    status: Hedra.GenerationStatus;
    /** Current progress to completion. Between 0-1 */
    progress: number;
    /** Estimated time until completion in seconds. May be None if no historical data available. */
    eta_sec?: (number | null) | undefined;
    /** Unique identifier linking all generations in a batch. */
    batch_generation_id?: (string | null) | undefined;
    /** All generation results in the batch. Always populated (even for batch_size=1). The main response fields (id, asset_id, etc.) reflect the first successful generation. */
    batch_results?: Hedra.BatchVideoResultItem[] | undefined;
}
