// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

export interface GeneratedImage {
    /** Width of the image. */
    width: number;
    /** Height of the image. */
    height: number;
    /** URL of the image. */
    url: string;
    /** Inputs for generating the image. */
    generated_image_inputs: Hedra.GeneratedImageInputs;
}
