// This file was auto-generated by Fern from our API Definition.

export interface GeneratedAudioInputs {
    /** Prompt for audio generation. */
    text_prompt: string;
    /** The id of the model used for generation. */
    ai_model_id?: (string | null) | undefined;
    /** The id of the voice used for generation. */
    voice_id?: (string | null) | undefined;
    /** Stability setting used for generation (0-1). */
    stability?: (number | null) | undefined;
    /** Speed setting used for generation (0.7-1.2). */
    speed?: (number | null) | undefined;
    /** Language used for generation. */
    language?: (string | null) | undefined;
}
