// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

export type GenerateAssetResponse =
    | Hedra.GenerateAssetResponse.Video
    | Hedra.GenerateAssetResponse.TextToSpeech
    | Hedra.GenerateAssetResponse.TextToSound
    | Hedra.GenerateAssetResponse.Image
    | Hedra.GenerateAssetResponse.ImageToImage
    | Hedra.GenerateAssetResponse.ImageUpscale
    | Hedra.GenerateAssetResponse.VideoUpscale
    | Hedra.GenerateAssetResponse.AudioIsolation
    | Hedra.GenerateAssetResponse.SpeechToSpeech
    | Hedra.GenerateAssetResponse.VoiceClone
    | Hedra.GenerateAssetResponse.AudioFromVideo
    | Hedra.GenerateAssetResponse.VideoWithAudio
    | Hedra.GenerateAssetResponse.VideoToVideo
    | Hedra.GenerateAssetResponse.MotionControl;

export namespace GenerateAssetResponse {
    export interface Video extends Hedra.GenerateVideoResponse {
        type: "video";
    }

    export interface TextToSpeech extends Hedra.GenerateTextToSpeechResponse {
        type: "text_to_speech";
    }

    export interface TextToSound extends Hedra.GenerateTextToSoundResponse {
        type: "text_to_sound";
    }

    export interface Image extends Hedra.GenerateImageResponse {
        type: "image";
    }

    export interface ImageToImage extends Hedra.GenerateImageResponse {
        type: "image_to_image";
    }

    export interface ImageUpscale extends Hedra.GenerateImageUpscaleResponse {
        type: "image_upscale";
    }

    export interface VideoUpscale extends Hedra.GenerateVideoUpscaleResponse {
        type: "video_upscale";
    }

    export interface AudioIsolation extends Hedra.GenerateIsolatedAudioResponse {
        type: "audio_isolation";
    }

    export interface SpeechToSpeech extends Hedra.GenerateSpeechToSpeechResponse {
        type: "speech_to_speech";
    }

    export interface VoiceClone extends Hedra.GenerateVoiceCloneResponse {
        type: "voice_clone";
    }

    export interface AudioFromVideo extends Hedra.GenerateAudioFromVideoResponse {
        type: "audio_from_video";
    }

    export interface VideoWithAudio extends Hedra.GenerateVideoWithAudioResponse {
        type: "video_with_audio";
    }

    export interface VideoToVideo extends Hedra.GenerateVideoToVideoResponse {
        type: "video_to_video";
    }

    export interface MotionControl extends Hedra.GenerateMotionControlResponse {
        type: "motion_control";
    }
}
