// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

export interface GeneratedVideo {
    /** Width of the image. */
    width: number;
    /** Height of the image. */
    height: number;
    /** URL of the image. */
    url?: (string | null) | undefined;
    /** URL to download the video */
    download_url?: (string | null) | undefined;
    /** URL to stream the video */
    streaming_url?: (string | null) | undefined;
    /** URL of the poster image */
    poster_url?: (string | null) | undefined;
    /** Duration of the video. */
    duration_ms: number;
    /** URL of the preview for animated thumbnails. */
    preview_url: string;
    /** Inputs for generating the video. */
    generated_video_inputs: Hedra.GeneratedVideoInputs;
    /** URL of the Image asset used as the start keyframe. */
    keyframe_start: Hedra.Asset | null;
    /** URL of the Image asset used as the end keyframe. */
    keyframe_end?: (Hedra.Asset | null) | undefined;
    /** URL of the Audio asset used as the basis for the video. */
    audio: Hedra.Asset | null;
    /** The id(s) of the image(s) referenced in the generation. */
    reference_image_ids?: (string[] | null) | undefined;
    /** The id of the Video asset used as source input for motion control/video-to-video generation. */
    source_video_id?: (string | null) | undefined;
}
