// This file was auto-generated by Fern from our API Definition.

export interface GenerateImageRequest {
    workspace_id?: (string | null) | undefined;
    /** Optional agent thread ID to associate this generation with. */
    agent_thread_id?: (string | null) | undefined;
    /** Optional pre-reserved generation ID. If provided, this ID will be used instead of generating a new one. For batch operations (batch_size > 1), use generation_ids instead. */
    generation_id?: (string | null) | undefined;
    /** Optional list of pre-reserved generation IDs for batch operations. Length must match batch_size. Mutually exclusive with generation_id. */
    generation_ids?: (string[] | null) | undefined;
    /** The text prompt for image generation or image editing. */
    text_prompt: string;
    /** The aspect ratio to use. */
    aspect_ratio?: (string | null) | undefined;
    /** The resolution to use formatted like '540p', '1080p', '1440p (2K QHD)', etc. */
    resolution?: (string | null) | undefined;
    /** The id of the Image asset to use as the start keyframe. This will be ignored if reference_image_ids is provided. */
    start_keyframe_id?: (string | null) | undefined;
    /** The model to use. */
    ai_model_id: string;
    /** The id(s) of the image(s) to reference in the generation. This is only used for image-to-image generation and will supersede start_keyframe_id. */
    reference_image_ids?: (string[] | null) | undefined;
    /** Number of image variations to generate (1-8). When > 1, batch_results will contain all generation results. */
    batch_size?: number | undefined;
    /** If true, automatically enhance the prompt before generation. */
    enhance_prompt?: boolean | undefined;
}
