// This file was auto-generated by Fern from our API Definition.

export interface GenerateImageUpscaleRequest {
    workspace_id?: (string | null) | undefined;
    /** Optional agent thread ID to associate this generation with. */
    agent_thread_id?: (string | null) | undefined;
    /** Optional pre-reserved generation ID. If provided, this ID will be used instead of generating a new one. For batch operations (batch_size > 1), use generation_ids instead. */
    generation_id?: (string | null) | undefined;
    /** Optional list of pre-reserved generation IDs for batch operations. Length must match batch_size. Mutually exclusive with generation_id. */
    generation_ids?: (string[] | null) | undefined;
    /** The model to use for upscaling. */
    ai_model_id: string;
    /** The id of the Image asset to use as the basis for upscaling. */
    image_id: string;
    /** Optional upscale factor to pass to the model (e.g. 2.0 for 2x). */
    upscale_factor?: (number | null) | undefined;
}
