// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `kling-o1`.
 *
 * Accepted field combinations (one per input mode):
 * (1) requires: aspect_ratio, duration_ms, prompt, start_image
 * (2) requires: aspect_ratio, duration_ms, images, prompt
 */
export interface InputKlingO1 {
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Generation prompt. At most 2500 characters. */
    prompt: string;
    /** Output aspect ratio. */
    aspect_ratio: InputKlingO1.AspectRatio;
    /** Output resolution. */
    resolution?: InputKlingO1.Resolution | undefined;
    /** Duration in ms. */
    duration_ms: number;
    /** Start frame. At most 10.4 MB. */
    start_image?: Hedra.InputKlingO1StartImage | undefined;
    /** End frame. At most 10.4 MB. */
    end_image?: Hedra.InputKlingO1EndImage | undefined;
    /** Reference images. 1 to 3 images, each at most 10.4 MB. */
    images?: Hedra.InputKlingO1ImagesItem[] | undefined;
}

export namespace InputKlingO1 {
    /** Output aspect ratio. */
    export const AspectRatio = {
        Sixteen9: "16:9",
        Nine16: "9:16",
        One1: "1:1",
    } as const;
    export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];
    /** Output resolution. */
    export const Resolution = {
        OneThousandEightyP: "1080p",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
}
