// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `reve-21-edit`.
 */
export interface InputReve21Edit {
    /** Generation prompt. */
    prompt: string;
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Rewrite the prompt before generation. An LLM expands it into a fuller description and the model receives that text instead of the submitted one; the result's `prompt` reports what ran. */
    enhance_prompt?: boolean | undefined;
    /** Output aspect ratio. */
    aspect_ratio: InputReve21Edit.AspectRatio;
    /** The single source image to edit. */
    images: Hedra.InputReve21EditImagesItem[];
    /** Output image format. */
    output_format?: InputReve21Edit.OutputFormat | undefined;
}

export namespace InputReve21Edit {
    /** Output aspect ratio. */
    export const AspectRatio = {
        Four1: "4:1",
        Three1: "3:1",
        TwentyOne9: "21:9",
        Two1: "2:1",
        Seventeen9: "17:9",
        Sixteen9: "16:9",
        Three2: "3:2",
        Four3: "4:3",
        Five4: "5:4",
        One1: "1:1",
        Four5: "4:5",
        Three4: "3:4",
        Two3: "2:3",
        Nine16: "9:16",
        One2: "1:2",
        One3: "1:3",
        One4: "1:4",
    } as const;
    export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];
    /** Output image format. */
    export const OutputFormat = {
        Jpeg: "jpeg",
        Png: "png",
        Webp: "webp",
    } as const;
    export type OutputFormat = (typeof OutputFormat)[keyof typeof OutputFormat];
}
