// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `veo-2`.
 */
export interface InputVeo2 {
    num_outputs?: number | undefined;
    /** Generation prompt. */
    prompt: string;
    /** Output aspect ratio. */
    aspect_ratio?: InputVeo2.AspectRatio | undefined;
    /** Output resolution. */
    resolution?: InputVeo2.Resolution | undefined;
    /** Duration in ms. */
    duration_ms?: number | undefined;
    /** What to avoid in the generated video. */
    negative_prompt?: string | undefined;
    /** Seed for reproducible output; omit for a random seed. */
    seed?: number | undefined;
    /** Start frame (image-to-video). */
    start_image?: Hedra.InputVeo2StartImage | undefined;
}

export namespace InputVeo2 {
    /** Output aspect ratio. */
    export const AspectRatio = {
        Sixteen9: "16:9",
    } as const;
    export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];
    /** Output resolution. */
    export const Resolution = {
        SevenHundredTwentyP: "720p",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
}
