// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `flux-3-video-upscaler-precise`.
 */
export interface InputFlux3VideoUpscalerPrecise {
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** The video to upscale. At most 20s and at most 524.2 MB. */
    source_video: Hedra.InputFlux3VideoUpscalerPreciseSourceVideo;
    /** Output resolution. */
    resolution: InputFlux3VideoUpscalerPrecise.Resolution;
}

export namespace InputFlux3VideoUpscalerPrecise {
    /** Output resolution. */
    export const Resolution = {
        OneThousandEightyP: "1080p",
        TwoK: "2K",
        FourK: "4K",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
}
