// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `kling-v3`.
 *
 * Accepted field combinations (one per input mode):
 * (1) requires: aspect_ratio, duration_ms, resolution, start_image; must omit: end_image; accepts quality: pro; resolution: 1080p | 4K
 * (2) requires: aspect_ratio, duration_ms, end_image, resolution, start_image; accepts quality: pro; resolution: 1080p | 4K
 * (3) requires: aspect_ratio, duration_ms, resolution; must omit: end_image, start_image; accepts quality: pro; resolution: 1080p | 4K
 * (4) requires: aspect_ratio, duration_ms, start_image; must omit: end_image; accepts quality: standard; resolution: 720p
 * (5) requires: aspect_ratio, duration_ms, end_image, start_image; accepts quality: standard; resolution: 720p
 * (6) requires: aspect_ratio, duration_ms; must omit: end_image, start_image; accepts quality: standard; resolution: 720p
 */
export interface InputKlingV3 {
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Generation prompt. At most 2500 characters. */
    prompt?: string | undefined;
    /** Multi-shot storyboard; each shot carries its own prompt and duration. Shot durations must sum to at most 15000 ms, and the storyboard replaces `prompt` — supply one or the other, never both. A shot's prompt has no length limit, unlike the single `prompt` field. 1 to 6 items. */
    multi_prompt?: InputKlingV3.MultiPrompt.Item[] | undefined;
    /** How a multi-shot storyboard is cut. 'customize' honours each shot's declared duration; 'intelligent' lets the model determine the shot structure. Ignored unless `multi_prompt` is supplied. */
    shot_type?: InputKlingV3.ShotType | undefined;
    /** Whether to generate native audio for the video. */
    generate_audio?: boolean | undefined;
    /** What to avoid in the generated video. At most 2500 characters. */
    negative_prompt?: string | undefined;
    /** Output aspect ratio. */
    aspect_ratio: InputKlingV3.AspectRatio;
    /** Output resolution. */
    resolution?: InputKlingV3.Resolution | undefined;
    /** Duration in ms. */
    duration_ms: number;
    /** Start frame (image-to-video). At most 10.4 MB. */
    start_image?: Hedra.InputKlingV3StartImage | undefined;
    /** How closely the model follows the prompt. From 0 to 1. */
    cfg_scale?: number | undefined;
    /** End frame (first-last-frame-to-video). At most 10.4 MB. */
    end_image?: Hedra.InputKlingV3EndImage | undefined;
    /** Quality level to generate at. */
    quality: InputKlingV3.Quality;
}

export namespace InputKlingV3 {
    export type MultiPrompt = MultiPrompt.Item[];

    export namespace MultiPrompt {
        /**
         * One shot of a published multi-shot storyboard.
         */
        export interface Item {
            /** The prompt for this shot. */
            prompt: string;
            /** Duration of this shot in milliseconds. */
            duration_ms?: number | undefined;
        }
    }

    /** How a multi-shot storyboard is cut. 'customize' honours each shot's declared duration; 'intelligent' lets the model determine the shot structure. Ignored unless `multi_prompt` is supplied. */
    export const ShotType = {
        Customize: "customize",
        Intelligent: "intelligent",
    } as const;
    export type ShotType = (typeof ShotType)[keyof typeof ShotType];
    /** Output aspect ratio. */
    export const AspectRatio = {
        Sixteen9: "16:9",
        Nine16: "9:16",
        One1: "1:1",
    } as const;
    export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];
    /** Output resolution. */
    export const Resolution = {
        OneThousandEightyP: "1080p",
        FourK: "4K",
        SevenHundredTwentyP: "720p",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
    /** Quality level to generate at. */
    export const Quality = {
        Standard: "standard",
        Pro: "pro",
    } as const;
    export type Quality = (typeof Quality)[keyof typeof Quality];
}
