// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `pixverse-v6`.
 *
 * Accepted field combinations (one per input mode):
 * (1) requires: aspect_ratio, duration_ms, prompt, resolution; must omit: start_image
 * (2) requires: duration_ms, prompt, resolution, start_image; must omit: aspect_ratio
 */
export interface InputPixverseV6 {
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Generation prompt. */
    prompt: string;
    /** Output resolution. */
    resolution: InputPixverseV6.Resolution;
    /** Duration in ms. */
    duration_ms: number;
    /** Whether to generate native audio for the video. */
    generate_audio?: boolean | undefined;
    /** What to avoid in the generated video. */
    negative_prompt?: string | undefined;
    /** Seed for reproducible output; omit for a random seed. */
    seed?: number | undefined;
    /** Output aspect ratio. */
    aspect_ratio?: InputPixverseV6.AspectRatio | undefined;
    /** Start frame (image-to-video). */
    start_image?: Hedra.InputPixverseV6StartImage | undefined;
}

export namespace InputPixverseV6 {
    /** Output resolution. */
    export const Resolution = {
        ThreeHundredSixtyP: "360p",
        FiveHundredFortyP: "540p",
        SevenHundredTwentyP: "720p",
        OneThousandEightyP: "1080p",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
    /** Output aspect ratio. */
    export const AspectRatio = {
        Sixteen9: "16:9",
        Four3: "4:3",
        One1: "1:1",
        Three4: "3:4",
        Nine16: "9:16",
        Two3: "2:3",
        Three2: "3:2",
        TwentyOne9: "21:9",
    } as const;
    export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];
}
