// This file was auto-generated by Fern from our API Definition.

/**
 * Model-specific inputs for `ideogram-v2`.
 */
export interface InputIdeogramV2 {
    /** Generation prompt. */
    prompt: string;
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Rewrite the prompt before generation. An LLM expands it into a fuller description and the model receives that text instead of the submitted one; the result's `prompt` reports what ran. */
    enhance_prompt?: boolean | undefined;
    /** Output aspect ratio. */
    aspect_ratio: InputIdeogramV2.AspectRatio;
    /** Output resolution. */
    resolution?: InputIdeogramV2.Resolution | undefined;
    /** What to avoid in the generated image. */
    negative_prompt?: string | undefined;
    /** Seed for reproducible output; omit for a random seed. */
    seed?: number | undefined;
}

export namespace InputIdeogramV2 {
    /** Output aspect ratio. */
    export const AspectRatio = {
            One1: "1:1",
            One3: "1:3",
            Two3: "2:3",
            Three1: "3:1",
            Three2: "3:2",
            Three4: "3:4",
            Four3: "4:3",
            Sixteen9: "16:9",
            Nine16: "9:16",
            Ten16: "10:16",
            Sixteen10: "16:10"
        } as const;
    export type AspectRatio = typeof AspectRatio[keyof typeof AspectRatio];
    /** Output resolution. */
    export const Resolution = {
            Fixed: "fixed"
        } as const;
    export type Resolution = typeof Resolution[keyof typeof Resolution];
}
