// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `topaz-video-upscaler-starlight-hq`.
 */
export interface InputTopazVideoUpscalerStarlightHq {
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** The video to upscale. At most 300s and at most 524.2 MB. */
    source_video: Hedra.InputTopazVideoUpscalerStarlightHqSourceVideo;
    /** Output resolution. */
    resolution: InputTopazVideoUpscalerStarlightHq.Resolution;
    /** Soften the diffusion pass, which suits sources the default sharpening renders harshly. */
    reduce_sharpening?: boolean | undefined;
}

export namespace InputTopazVideoUpscalerStarlightHq {
    /** Output resolution. */
    export const Resolution = {
        OneThousandEightyP: "1080p",
        TwoK: "2K",
        FourK: "4K",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
}
