// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `flux-3`.
 *
 * Accepted field combinations (one per input mode):
 * (1) requires: aspect_ratio, duration_ms, prompt, resolution, start_image; must omit: end_image
 * (2) requires: aspect_ratio, duration_ms, end_image, prompt, resolution, start_image
 * (3) requires: aspect_ratio, duration_ms, prompt, resolution; must omit: end_image, start_image
 */
export interface InputFlux3 {
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Generation prompt. */
    prompt: string;
    /** Output aspect ratio. */
    aspect_ratio: InputFlux3.AspectRatio;
    /** Output resolution. */
    resolution: InputFlux3.Resolution;
    /** Duration in ms. */
    duration_ms: number;
    /** Whether to generate native audio for the video. */
    generate_audio?: boolean | undefined;
    /** Start frame (image-to-video). */
    start_image?: Hedra.InputFlux3StartImage | undefined;
    /** End frame (first-last-frame-to-video). */
    end_image?: Hedra.InputFlux3EndImage | undefined;
}

export namespace InputFlux3 {
    /** Output aspect ratio. */
    export const AspectRatio = {
        Auto: "auto",
        TwentyOne9: "21:9",
        Two1: "2:1",
        Sixteen9: "16:9",
        Four3: "4:3",
        One1: "1:1",
        Three4: "3:4",
        Nine16: "9:16",
    } as const;
    export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];
    /** Output resolution. */
    export const Resolution = {
        SevenHundredTwentyP: "720p",
        OneThousandEightyP: "1080p",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
}
