// This file was auto-generated by Fern from our API Definition.

import * as Hedra from "../index.js";

/**
 * Model-specific inputs for `veo-31`.
 */
export interface InputVeo31 {
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Generation prompt. */
    prompt: string;
    /** Output aspect ratio. */
    aspect_ratio: InputVeo31.AspectRatio;
    /** Output resolution. */
    resolution: InputVeo31.Resolution;
    /** Duration in ms. */
    duration_ms?: number | undefined;
    /** Whether to generate native audio for the video. */
    generate_audio?: boolean | undefined;
    /** What to avoid in the generated video. */
    negative_prompt?: string | undefined;
    /** Start frame (image-to-video). */
    start_image?: Hedra.InputVeo31StartImage | undefined;
    /** End frame (first-last-frame-to-video). */
    end_image?: Hedra.InputVeo31EndImage | undefined;
    /** Source video (video-to-video). */
    source_video?: Hedra.InputVeo31SourceVideo | undefined;
    /** Reference images. */
    images?: Hedra.InputVeo31ImagesItem[] | undefined;
    /** Seed for reproducible output; omit for a random seed. */
    seed?: number | undefined;
    /** Quality level to generate at. */
    quality: InputVeo31.Quality;
}

export namespace InputVeo31 {
    /** Output aspect ratio. */
    export const AspectRatio = {
            Sixteen9: "16:9",
            Nine16: "9:16"
        } as const;
    export type AspectRatio = typeof AspectRatio[keyof typeof AspectRatio];
    /** Output resolution. */
    export const Resolution = {
            SevenHundredTwentyP: "720p",
            OneThousandEightyP: "1080p"
        } as const;
    export type Resolution = typeof Resolution[keyof typeof Resolution];
    /** Quality level to generate at. */
    export const Quality = {
            Standard: "standard",
            Fast: "fast"
        } as const;
    export type Quality = typeof Quality[keyof typeof Quality];
}
