// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `kling-v3`.
 */
export interface InputKlingV3 {
    num_outputs?: number | undefined;
    /** Generation prompt. */
    prompt: string;
    /** Whether to generate native audio for the video. */
    generate_audio?: boolean | undefined;
    /** What to avoid in the generated video. */
    negative_prompt?: string | undefined;
    /** Output aspect ratio. */
    aspect_ratio: InputKlingV3.AspectRatio;
    /** Output resolution. */
    resolution?: InputKlingV3.Resolution | undefined;
    /** Duration in ms. */
    duration_ms: number;
    /** Start frame (image-to-video). */
    start_image?: Hedra.InputKlingV3StartImage | undefined;
    /** End frame (first-last-frame-to-video). */
    end_image?: Hedra.InputKlingV3EndImage | undefined;
    /** How closely the model follows the prompt. */
    cfg_scale?: number | undefined;
    /** Quality level to generate at. */
    quality: InputKlingV3.Quality;
}

export namespace InputKlingV3 {
    /** Output aspect ratio. */
    export const AspectRatio = {
        Sixteen9: "16:9",
        Nine16: "9:16",
        One1: "1:1",
    } as const;
    export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];
    /** Output resolution. */
    export const Resolution = {
        OneThousandEightyP: "1080p",
        FourK: "4K",
        SevenHundredTwentyP: "720p",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
    /** Quality level to generate at. */
    export const Quality = {
        Standard: "standard",
        Pro: "pro",
    } as const;
    export type Quality = (typeof Quality)[keyof typeof Quality];
}
