// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `hedra-character-3`.
 */
export interface InputHedraCharacter3 {
    num_outputs?: number | undefined;
    /** Generation prompt. */
    prompt: string;
    /** Output aspect ratio. */
    aspect_ratio: InputHedraCharacter3.AspectRatio;
    /** Output resolution. */
    resolution: InputHedraCharacter3.Resolution;
    /** Duration in ms. */
    duration_ms?: number | undefined;
    /** Start frame (image-to-video). */
    start_image: Hedra.InputHedraCharacter3StartImage;
    /** Driving audio. */
    audio: Hedra.InputHedraCharacter3Audio;
}

export namespace InputHedraCharacter3 {
    /** Output aspect ratio. */
    export const AspectRatio = {
        One1: "1:1",
        Four3: "4:3",
        Three4: "3:4",
        Sixteen9: "16:9",
        Nine16: "9:16",
        Nine21: "9:21",
        TwentyOne9: "21:9",
    } as const;
    export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];
    /** Output resolution. */
    export const Resolution = {
        FiveHundredFortyP: "540p",
        SevenHundredTwentyP: "720p",
        OneThousandEightyP: "1080p",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
}
