// This file was auto-generated by Fern from our API Definition.

/**
 * Model-specific inputs for `luma-ray-32`.
 */
export interface InputLumaRay32 {
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Generation prompt. */
    prompt: string;
    /** Output aspect ratio. */
    aspect_ratio: InputLumaRay32.AspectRatio;
    /** Output resolution. */
    resolution: InputLumaRay32.Resolution;
    /** Duration in ms. */
    duration_ms: number;
}

export namespace InputLumaRay32 {
    /** Output aspect ratio. */
    export const AspectRatio = {
            One1: "1:1",
            Three4: "3:4",
            Four3: "4:3",
            Sixteen9: "16:9",
            TwentyOne9: "21:9",
            Nine16: "9:16"
        } as const;
    export type AspectRatio = typeof AspectRatio[keyof typeof AspectRatio];
    /** Output resolution. */
    export const Resolution = {
            FiveHundredFortyP: "540p",
            SevenHundredTwentyP: "720p",
            OneThousandEightyP: "1080p"
        } as const;
    export type Resolution = typeof Resolution[keyof typeof Resolution];
}
