// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `kling-16`.
 *
 * Accepted field combinations (one per input mode):
 * (1) requires: prompt; must omit: start_image; accepts resolution: 720p
 * (2) requires: prompt, start_image; accepts resolution: 1080p
 */
export interface InputKling16 {
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Generation prompt. */
    prompt: string;
    /** Output aspect ratio. */
    aspect_ratio?: InputKling16.AspectRatio | undefined;
    /** Output resolution. */
    resolution?: InputKling16.Resolution | undefined;
    /** Duration in ms. */
    duration_ms?: number | undefined;
    /** Start frame (image-to-video). */
    start_image?: Hedra.InputKling16StartImage | undefined;
    /** What to avoid in the generated video. */
    negative_prompt?: string | undefined;
    /** How closely the model follows the prompt. */
    cfg_scale?: number | undefined;
}

export namespace InputKling16 {
    /** Output aspect ratio. */
    export const AspectRatio = {
        Sixteen9: "16:9",
    } as const;
    export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];
    /** Output resolution. */
    export const Resolution = {
        OneThousandEightyP: "1080p",
        SevenHundredTwentyP: "720p",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
}
