// This file was auto-generated by Fern from our API Definition.

/**
 * Model-specific inputs for `minimax-speech-25-hd-preview`.
 */
export interface InputMinimaxSpeech25HdPreview {
    /** Generation prompt. */
    text: string;
    stability?: number | undefined;
    speed?: number | undefined;
    /** Language code; 'auto' by default. */
    language?: string | undefined;
    /** Voice to speak with (`voice_<uuid>`). List valid voices at GET /v3/models/minimax-speech-25-hd-preview/voices. */
    voice_id: string;
}
