// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `minimax-hailuo-23`.
 */
export interface InputMinimaxHailuo23 {
    num_outputs?: number | undefined;
    /** Generation prompt. */
    prompt: string;
    /** Output aspect ratio. */
    aspect_ratio?: InputMinimaxHailuo23.AspectRatio | undefined;
    /** Output resolution. */
    resolution?: InputMinimaxHailuo23.Resolution | undefined;
    /** Duration in ms. */
    duration_ms: number;
    /** Start frame (image-to-video). */
    start_image?: Hedra.InputMinimaxHailuo23StartImage | undefined;
    /** Quality level to generate at. */
    quality: InputMinimaxHailuo23.Quality;
}

export namespace InputMinimaxHailuo23 {
    /** Output aspect ratio. */
    export const AspectRatio = {
        Sixteen9: "16:9",
    } as const;
    export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];
    /** Output resolution. */
    export const Resolution = {
        SevenHundredSixtyEightP: "768p",
        OneThousandEightyP: "1080p",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
    /** Quality level to generate at. */
    export const Quality = {
        Standard: "standard",
        Pro: "pro",
        FastStandard: "fast-standard",
        FastPro: "fast-pro",
    } as const;
    export type Quality = (typeof Quality)[keyof typeof Quality];
}
