// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * End frame (first-last-frame-to-video).
 */
export type InputKlingO3EndImage =
    /**
     * A file uploaded via POST /v3/files, referenced by the returned url. */
    | Hedra.InputKlingO3EndImage.Url
    /**
     * An existing asset you own, referenced by its id. */
    | Hedra.InputKlingO3EndImage.Asset;

export namespace InputKlingO3EndImage {
    export interface Url {
        source: "url";
        /** A URL returned by POST /v3/files. */
        url: string;
    }

    export interface Asset {
        source: "asset";
        /** The asset's id (`asset_<uuid>`). A completed job's output asset carries the job's UUID: replace the `job_` prefix with `asset_`. */
        asset_id: string;
    }
}
