// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `omnihuman-15`.
 */
export interface InputOmnihuman15 {
    num_outputs?: number | undefined;
    /** Generation prompt. */
    prompt?: string | undefined;
    /** Output aspect ratio. */
    aspect_ratio?: InputOmnihuman15.AspectRatio | undefined;
    /** Output resolution. */
    resolution?: InputOmnihuman15.Resolution | undefined;
    /** Start frame (image-to-video). */
    start_image: Hedra.InputOmnihuman15StartImage;
    /** Driving audio. */
    audio: Hedra.InputOmnihuman15Audio;
}

export namespace InputOmnihuman15 {
    /** Output aspect ratio. */
    export const AspectRatio = {
        Sixteen9: "16:9",
    } as const;
    export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];
    /** Output resolution. */
    export const Resolution = {
        SevenHundredTwentyP: "720p",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
}
