// This file was auto-generated by Fern from our API Definition.

import * as Hedra from "../index.js";

/**
 * Model-specific inputs for `ltx-2-3`.
 *
 * Accepted field combinations (one per input mode):
 * (1) requires: aspect_ratio, duration_ms, prompt, resolution; must omit: end_image, start_image; accepts aspect_ratio: 16:9 | 9:16; duration_ms: 6000 | 8000 | 10000; quality: pro
 * (2) requires: aspect_ratio, duration_ms, prompt, resolution; must omit: end_image, start_image; accepts aspect_ratio: 16:9 | 9:16; quality: fast
 * (3) requires: aspect_ratio, duration_ms, prompt, resolution, start_image; accepts duration_ms: 6000 | 8000 | 10000; quality: pro
 * (4) requires: aspect_ratio, duration_ms, prompt, resolution, start_image; accepts quality: fast
 */
export interface InputLtx23 {
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Generation prompt. */
    prompt: string;
    /** Output resolution. */
    resolution: InputLtx23.Resolution;
    /** Whether to generate native audio for the video. */
    generate_audio?: boolean | undefined;
    /** Duration in ms. */
    duration_ms: number;
    /** Output aspect ratio. */
    aspect_ratio: InputLtx23.AspectRatio;
    /** Start frame (image-to-video). */
    start_image?: Hedra.InputLtx23StartImage | undefined;
    /** End frame (first-last-frame-to-video). */
    end_image?: Hedra.InputLtx23EndImage | undefined;
    /** Quality level to generate at. */
    quality: InputLtx23.Quality;
}

export namespace InputLtx23 {
    /** Output resolution. */
    export const Resolution = {
            OneThousandEightyP: "1080p",
            OneThousandFourHundredFortyP: "1440p",
            TwoThousandOneHundredSixtyP: "2160p"
        } as const;
    export type Resolution = typeof Resolution[keyof typeof Resolution];
    /** Output aspect ratio. */
    export const AspectRatio = {
            Sixteen9: "16:9",
            Nine16: "9:16",
            Auto: "auto"
        } as const;
    export type AspectRatio = typeof AspectRatio[keyof typeof AspectRatio];
    /** Quality level to generate at. */
    export const Quality = {
            Fast: "fast",
            Pro: "pro"
        } as const;
    export type Quality = typeof Quality[keyof typeof Quality];
}
