// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `flux2-klein-9b`.
 *
 * Accepted field combinations (one per input mode):
 * (1) requires: aspect_ratio, images, prompt
 * (2) requires: aspect_ratio, prompt; must omit: images
 */
export interface InputFlux2Klein9B {
    /** Generation prompt. */
    prompt: string;
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Rewrite the prompt before generation. An LLM expands it into a fuller description and the model receives that text instead of the submitted one; the result's `prompt` reports what ran. */
    enhance_prompt?: boolean | undefined;
    /** Output aspect ratio. */
    aspect_ratio: InputFlux2Klein9B.AspectRatio;
    /** Images to edit or blend. 1 to 4 images, each at most 30 MB. */
    images?: Hedra.InputFlux2Klein9BImagesItem[] | undefined;
    /** Output image format. */
    output_format?: InputFlux2Klein9B.OutputFormat | undefined;
    /** What to avoid in the generated image. */
    negative_prompt?: string | undefined;
    /** Seed for reproducible output; omit for a random seed. */
    seed?: number | undefined;
    /** How closely the model follows the prompt. From 0 to 20. */
    guidance_scale?: number | undefined;
    /** Denoising steps to run. From 4 to 50. */
    num_inference_steps?: number | undefined;
}

export namespace InputFlux2Klein9B {
    /** Output aspect ratio. */
    export const AspectRatio = {
        Sixteen9: "16:9",
        Nine16: "9:16",
        Four3: "4:3",
        Three4: "3:4",
        One1: "1:1",
    } as const;
    export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];
    /** Output image format. */
    export const OutputFormat = {
        Jpeg: "jpeg",
        Png: "png",
        Webp: "webp",
    } as const;
    export type OutputFormat = (typeof OutputFormat)[keyof typeof OutputFormat];
}
