// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `seedance-20-mini`.
 */
export interface InputSeedance20Mini {
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Generation prompt. */
    prompt: string;
    /** Output aspect ratio. */
    aspect_ratio: InputSeedance20Mini.AspectRatio;
    /** Output resolution. */
    resolution: InputSeedance20Mini.Resolution;
    /** Duration in ms. */
    duration_ms: number;
    /** Start frame (image-to-video). */
    start_image?: Hedra.InputSeedance20MiniStartImage | undefined;
    /** End frame (first-last-frame-to-video). */
    end_image?: Hedra.InputSeedance20MiniEndImage | undefined;
    /** Reference images. */
    images?: Hedra.InputSeedance20MiniImagesItem[] | undefined;
    /** Reference videos. */
    videos?: Hedra.InputSeedance20MiniVideosItem[] | undefined;
    /** Reference audios. */
    audios?: Hedra.InputSeedance20MiniAudiosItem[] | undefined;
}

export namespace InputSeedance20Mini {
    /** Output aspect ratio. */
    export const AspectRatio = {
        One1: "1:1",
        Three4: "3:4",
        Four3: "4:3",
        Sixteen9: "16:9",
        TwentyOne9: "21:9",
        Nine16: "9:16",
    } as const;
    export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];
    /** Output resolution. */
    export const Resolution = {
        FourHundredEightyP: "480p",
        SevenHundredTwentyP: "720p",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
}
