// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `creatify-aurora`.
 */
export interface InputCreatifyAurora {
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Generation prompt. */
    prompt?: string | undefined;
    /** Output resolution. */
    resolution: InputCreatifyAurora.Resolution;
    /** Start frame. At most 10.4 MB. */
    start_image: Hedra.InputCreatifyAuroraStartImage;
    /** Driving audio. At most 104.8 MB. */
    audio: Hedra.InputCreatifyAuroraAudio;
}

export namespace InputCreatifyAurora {
    /** Output resolution. */
    export const Resolution = {
        FourHundredEightyP: "480p",
        SevenHundredTwentyP: "720p",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
}
