// This file was auto-generated by Fern from our API Definition.

import * as Hedra from "../index.js";

/**
 * Model-specific inputs for `qwen-image-2`.
 *
 * Accepted field combinations (one per input mode):
 * (1) requires: aspect_ratio, images, prompt, resolution
 * (2) requires: aspect_ratio, prompt, resolution; must omit: images
 */
export interface InputQwenImage2 {
    /** Generation prompt. */
    prompt: string;
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Rewrite the prompt before generation. An LLM expands it into a fuller description and the model receives that text instead of the submitted one; the result's `prompt` reports what ran. */
    enhance_prompt?: boolean | undefined;
    /** Output aspect ratio. */
    aspect_ratio: InputQwenImage2.AspectRatio;
    /** Output resolution. */
    resolution: InputQwenImage2.Resolution;
    /** Output image format. */
    output_format?: InputQwenImage2.OutputFormat | undefined;
    /** What to avoid in the generated image. */
    negative_prompt?: string | undefined;
    /** Images to edit or blend. */
    images?: Hedra.InputQwenImage2ImagesItem[] | undefined;
    /** Seed for reproducible output; omit for a random seed. */
    seed?: number | undefined;
    /** Quality level to generate at. */
    quality: InputQwenImage2.Quality;
}

export namespace InputQwenImage2 {
    /** Output aspect ratio. */
    export const AspectRatio = {
            Sixteen9: "16:9",
            Nine16: "9:16",
            Four3: "4:3",
            Three4: "3:4",
            One1: "1:1"
        } as const;
    export type AspectRatio = typeof AspectRatio[keyof typeof AspectRatio];
    /** Output resolution. */
    export const Resolution = {
            FiveHundredFortyP: "540p",
            SevenHundredTwentyP: "720p",
            OneThousandEightyP: "1080p",
            OneThousandFourHundredFortyP2KQhd: "1440p (2K QHD)"
        } as const;
    export type Resolution = typeof Resolution[keyof typeof Resolution];
    /** Output image format. */
    export const OutputFormat = {
            Jpeg: "jpeg",
            Png: "png",
            Webp: "webp"
        } as const;
    export type OutputFormat = typeof OutputFormat[keyof typeof OutputFormat];
    /** Quality level to generate at. */
    export const Quality = {
            Standard: "standard",
            Pro: "pro"
        } as const;
    export type Quality = typeof Quality[keyof typeof Quality];
}
