// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `hedra-avatar`.
 */
export interface InputHedraAvatar {
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Generation prompt. */
    prompt: string;
    /** Output aspect ratio. */
    aspect_ratio: InputHedraAvatar.AspectRatio;
    /** Output resolution. */
    resolution: InputHedraAvatar.Resolution;
    /** Duration in ms. At most 600000. */
    duration_ms?: number | undefined;
    /** Start frame (image-to-video). At most 10.4 MB. */
    start_image: Hedra.InputHedraAvatarStartImage;
    /** Driving audio: a single reference, or a list of references for multi-speaker generation — one audio per speaker, played in list order. 1 to 4 audio files, each from 0.5s to 600s and at most 104.8 MB. */
    audio: InputHedraAvatar.Audio;
    /** Speaker position(s) in the start frame, as normalized [x, y] image coordinates (0-1 from the top-left). */
    bounding_box_target?: InputHedraAvatar.BoundingBoxTarget | undefined;
}

export namespace InputHedraAvatar {
    /** Output aspect ratio. */
    export const AspectRatio = {
        One1: "1:1",
        Four3: "4:3",
        Three4: "3:4",
        Sixteen9: "16:9",
        Nine16: "9:16",
        Nine21: "9:21",
        TwentyOne9: "21:9",
    } as const;
    export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];
    /** Output resolution. */
    export const Resolution = {
        FiveHundredFortyP: "540p",
        SevenHundredTwentyP: "720p",
        OneThousandEightyP: "1080p",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
    /**
     * Driving audio: a single reference, or a list of references for multi-speaker generation — one audio per speaker, played in list order. 1 to 4 audio files, each from 0.5s to 600s and at most 104.8 MB.
     */
    export type Audio = Hedra.InputHedraAvatarAudioZero | Hedra.InputHedraAvatarAudioOneItem[];
    /**
     * Speaker position(s) in the start frame, as normalized [x, y] image coordinates (0-1 from the top-left).
     */
    export type BoundingBoxTarget = unknown[] | unknown[][];
}
