// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `kling-21-master`.
 *
 * Accepted field combinations (one per input mode):
 * (1) requires: aspect_ratio, duration_ms, prompt, start_image
 * (2) requires: aspect_ratio, duration_ms, prompt; must omit: start_image
 */
export interface InputKling21Master {
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Generation prompt. At most 2500 characters. */
    prompt: string;
    /** Output aspect ratio. */
    aspect_ratio: InputKling21Master.AspectRatio;
    /** Output resolution. */
    resolution?: InputKling21Master.Resolution | undefined;
    /** Duration in ms. */
    duration_ms: number;
    /** Start frame (image-to-video). At most 10.4 MB. */
    start_image?: Hedra.InputKling21MasterStartImage | undefined;
    /** What to avoid in the generated video. At most 2500 characters. */
    negative_prompt?: string | undefined;
    /** How closely the model follows the prompt. From 0 to 1. */
    cfg_scale?: number | undefined;
}

export namespace InputKling21Master {
    /** Output aspect ratio. */
    export const AspectRatio = {
        Sixteen9: "16:9",
        Nine16: "9:16",
        One1: "1:1",
    } as const;
    export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];
    /** Output resolution. */
    export const Resolution = {
        SevenHundredTwentyP: "720p",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
}
