// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `topaz-image-upscaler-wonder`.
 */
export interface InputTopazImageUpscalerWonder {
    /** The image to upscale. At most 30 MB. */
    source_image: Hedra.InputTopazImageUpscalerWonderSourceImage;
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Short edge of the upscaled image. The long edge follows the source's aspect ratio. */
    target_resolution: InputTopazImageUpscalerWonder.TargetResolution;
    /** How far the generative pass may depart from the source. Lower values stay closer to the original pixels; higher values invent more detail. */
    enhancement_strength?: InputTopazImageUpscalerWonder.EnhancementStrength | undefined;
    /** Add film grain to the upscaled image, which hides the over-smooth look generative upscaling can leave. */
    film_grain?: boolean | undefined;
}

export namespace InputTopazImageUpscalerWonder {
    /** Short edge of the upscaled image. The long edge follows the source's aspect ratio. */
    export const TargetResolution = {
        OneThousandEightyP: "1080p",
        TwoK: "2K",
        FourK: "4K",
    } as const;
    export type TargetResolution = (typeof TargetResolution)[keyof typeof TargetResolution];
    /** How far the generative pass may depart from the source. Lower values stay closer to the original pixels; higher values invent more detail. */
    export const EnhancementStrength = {
        Low: "low",
        Medium: "medium",
        High: "high",
    } as const;
    export type EnhancementStrength = (typeof EnhancementStrength)[keyof typeof EnhancementStrength];
}
