// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * The SDR video to convert. Its frames may hold at most 14,745,600 pixels (5120x2880). At most 600s and at most 524.2 MB.
 */
export type InputTopazVideoUpscalerHyperion25SourceVideo =
    /**
     * A file uploaded via POST /v3/files, referenced by the returned url. */
    | Hedra.InputTopazVideoUpscalerHyperion25SourceVideo.Url
    /**
     * An existing asset you own, referenced by its id. */
    | Hedra.InputTopazVideoUpscalerHyperion25SourceVideo.Asset;

export namespace InputTopazVideoUpscalerHyperion25SourceVideo {
    export interface Url {
        source: "url";
        /** A URL returned by POST /v3/files. */
        url: string;
    }

    export interface Asset {
        source: "asset";
        /** The asset's id (`asset_<uuid>`), as issued by the server — a completed generation publishes one per output as `outputs[].asset_id`. Do not construct one or derive it from any other id. */
        asset_id: string;
    }
}
