// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `vidu-q3`.
 *
 * Accepted field combinations (one per input mode):
 * (1) requires: duration_ms, prompt, resolution, start_image; must omit: aspect_ratio, end_image
 * (2) requires: duration_ms, end_image, prompt, resolution, start_image; must omit: aspect_ratio
 * (3) requires: aspect_ratio, duration_ms, prompt, resolution; must omit: end_image, start_image
 */
export interface InputViduQ3 {
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Generation prompt. */
    prompt: string;
    /** Seed for reproducible output; omit for a random seed. */
    seed?: number | undefined;
    /** Output resolution. */
    resolution: InputViduQ3.Resolution;
    /** Duration in ms. */
    duration_ms: number;
    /** Start frame (image-to-video). */
    start_image?: Hedra.InputViduQ3StartImage | undefined;
    /** End frame (first-last-frame-to-video). */
    end_image?: Hedra.InputViduQ3EndImage | undefined;
    /** Output aspect ratio. */
    aspect_ratio?: InputViduQ3.AspectRatio | undefined;
    /** Quality level to generate at. */
    quality: InputViduQ3.Quality;
}

export namespace InputViduQ3 {
    /** Output resolution. */
    export const Resolution = {
        FiveHundredFortyP: "540p",
        SevenHundredTwentyP: "720p",
        OneThousandEightyP: "1080p",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
    /** Output aspect ratio. */
    export const AspectRatio = {
        Sixteen9: "16:9",
        Nine16: "9:16",
        Four3: "4:3",
        Three4: "3:4",
        One1: "1:1",
    } as const;
    export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];
    /** Quality level to generate at. */
    export const Quality = {
        Standard: "standard",
        Turbo: "turbo",
    } as const;
    export type Quality = (typeof Quality)[keyof typeof Quality];
}
