// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Video whose background should be made transparent. At most 120s and at most 524.2 MB.
 */
export type InputVeedVideoBackgroundRemovalSourceVideo =
    /**
     * A file uploaded via POST /v3/files, referenced by the returned url. */
    | Hedra.InputVeedVideoBackgroundRemovalSourceVideo.Url
    /**
     * An existing asset you own, referenced by its id. */
    | Hedra.InputVeedVideoBackgroundRemovalSourceVideo.Asset;

export namespace InputVeedVideoBackgroundRemovalSourceVideo {
    export interface Url {
        source: "url";
        /** A URL returned by POST /v3/files. */
        url: string;
    }

    export interface Asset {
        source: "asset";
        /** The asset's id (`asset_<uuid>`), as issued by the server — a completed generation publishes one per output as `outputs[].asset_id`. Do not construct one or derive it from any other id. */
        asset_id: string;
    }
}
