// This file was auto-generated by Fern from our API Definition.

/**
 * Model-specific inputs for `minimax-speech-25-hd-preview`.
 */
export interface InputMinimaxSpeech25HdPreview {
    /** Generation prompt. At most 9999 characters. */
    text: string;
    /** Voice stability. Higher values give a steadier, more consistent delivery; lower values allow more expressive variation between generations. From 0 to 1. */
    stability?: number | undefined;
    /** Speech rate multiplier; 1.0 is the voice's natural pace. From 0.7 to 1.2. */
    speed?: number | undefined;
    /** Language code; 'auto' by default. */
    language?: string | undefined;
    /** Voice to speak with (`voice_<uuid>`). List valid voices at GET /v3/models/minimax-speech-25-hd-preview/voices. */
    voice_id: string;
}
