// This file was auto-generated by Fern from our API Definition.

/**
 * Model-specific inputs for `elevenlabs-music`.
 */
export interface InputElevenlabsMusic {
    /** Generation prompt. */
    prompt: string;
    /** Length of the generated track, in milliseconds. Billed as whole seconds, rounded up. From 3000 to 600000. */
    duration_ms: number;
    /** Words for the track to sing. Sent to the provider inside the prompt, which reads lyrics from the prompt text and places them across the requested length. Cannot be combined with `force_instrumental`. At most 10000 characters. */
    lyrics?: string | undefined;
    /** Compose without vocals. */
    force_instrumental?: boolean | undefined;
}
