// This file was auto-generated by Fern from our API Definition.

import * as Hedra from "../index.js";

/**
 * Model-specific inputs for `mai-image-2-5`.
 *
 * Accepted field combinations (one per input mode):
 * (1) requires: aspect_ratio, images, prompt
 * (2) requires: aspect_ratio, prompt; must omit: images
 */
export interface InputMaiImage25 {
    /** Generation prompt. */
    prompt: string;
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Rewrite the prompt before generation. An LLM expands it into a fuller description and the model receives that text instead of the submitted one; the result's `prompt` reports what ran. */
    enhance_prompt?: boolean | undefined;
    /** Output aspect ratio. */
    aspect_ratio: InputMaiImage25.AspectRatio;
    /** The single source image to edit. */
    images?: Hedra.InputMaiImage25ImagesItem[] | undefined;
    /** Output image format. */
    output_format?: InputMaiImage25.OutputFormat | undefined;
    /** Quality level to generate at. */
    quality: InputMaiImage25.Quality;
}

export namespace InputMaiImage25 {
    /** Output aspect ratio. */
    export const AspectRatio = {
            One1: "1:1",
            Four3: "4:3",
            Three4: "3:4",
            Sixteen9: "16:9",
            Nine16: "9:16",
            Three2: "3:2",
            Two3: "2:3"
        } as const;
    export type AspectRatio = typeof AspectRatio[keyof typeof AspectRatio];
    /** Output image format. */
    export const OutputFormat = {
            Jpeg: "jpeg",
            Png: "png",
            Webp: "webp"
        } as const;
    export type OutputFormat = typeof OutputFormat[keyof typeof OutputFormat];
    /** Quality level to generate at. */
    export const Quality = {
            Standard: "standard",
            Pro: "pro"
        } as const;
    export type Quality = typeof Quality[keyof typeof Quality];
}
