// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `minimax-hailuo-02`.
 */
export interface InputMinimaxHailuo02 {
    num_outputs?: number | undefined;
    /** Generation prompt. */
    prompt: string;
    /** Output aspect ratio. */
    aspect_ratio?: InputMinimaxHailuo02.AspectRatio | undefined;
    /** Output resolution. */
    resolution?: InputMinimaxHailuo02.Resolution | undefined;
    /** Duration in ms. */
    duration_ms: number;
    /** Start frame (image-to-video). */
    start_image?: Hedra.InputMinimaxHailuo02StartImage | undefined;
    /** End frame (first-last-frame-to-video). */
    end_image?: Hedra.InputMinimaxHailuo02EndImage | undefined;
    /** Quality level to generate at. */
    quality: InputMinimaxHailuo02.Quality;
}

export namespace InputMinimaxHailuo02 {
    /** Output aspect ratio. */
    export const AspectRatio = {
        Sixteen9: "16:9",
    } as const;
    export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];
    /** Output resolution. */
    export const Resolution = {
        SevenHundredSixtyEightP: "768p",
        OneThousandEightyP: "1080p",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
    /** Quality level to generate at. */
    export const Quality = {
        Standard: "standard",
        Pro: "pro",
    } as const;
    export type Quality = (typeof Quality)[keyof typeof Quality];
}
