// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * End frame (first-last-frame-to-video). With an aspect ratio from 0.4 to 2.5 and at most 30 MB.
 */
export type InputSeedance15ProEndImage =
    /**
     * A file uploaded via POST /v3/files, referenced by the returned url. */
    | Hedra.InputSeedance15ProEndImage.Url
    /**
     * An existing asset you own, referenced by its id. */
    | Hedra.InputSeedance15ProEndImage.Asset;

export namespace InputSeedance15ProEndImage {
    export interface Url {
        source: "url";
        /** A URL returned by POST /v3/files. */
        url: string;
    }

    export interface Asset {
        source: "asset";
        /** The asset's id (`asset_<uuid>`), as issued by the server — a completed generation publishes one per output as `outputs[].asset_id`. Do not construct one or derive it from any other id. */
        asset_id: string;
    }
}
