// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Speech sample of the voice to clone. Longer, cleaner samples of a single speaker clone better. At most 104.8 MB.
 */
export type InputElevenlabsVoiceCloneAudio =
    /**
     * A file uploaded via POST /v3/files, referenced by the returned url. */
    | Hedra.InputElevenlabsVoiceCloneAudio.Url
    /**
     * An existing asset you own, referenced by its id. */
    | Hedra.InputElevenlabsVoiceCloneAudio.Asset;

export namespace InputElevenlabsVoiceCloneAudio {
    export interface Url {
        source: "url";
        /** A URL returned by POST /v3/files. */
        url: string;
    }

    export interface Asset {
        source: "asset";
        /** The asset's id (`asset_<uuid>`), as issued by the server — a completed generation publishes one per output as `outputs[].asset_id`. Do not construct one or derive it from any other id. */
        asset_id: string;
    }
}
