// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `veed-video-background-removal`.
 */
export interface InputVeedVideoBackgroundRemoval {
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Video whose background should be made transparent. At most 120s and at most 524.2 MB. */
    source_video: Hedra.InputVeedVideoBackgroundRemovalSourceVideo;
    /** Optimize segmentation for a person rather than an object. */
    subject_is_person?: boolean | undefined;
}
