// This file was auto-generated by Fern from our API Definition.

/**
 * Model-specific inputs for `imagen4`.
 */
export interface InputImagen4 {
    /** Generation prompt. At most 5000 characters. */
    prompt: string;
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Rewrite the prompt before generation. An LLM expands it into a fuller description and the model receives that text instead of the submitted one; the result's `prompt` reports what ran. */
    enhance_prompt?: boolean | undefined;
    /** Output aspect ratio. */
    aspect_ratio: InputImagen4.AspectRatio;
    /** Output resolution. */
    resolution: InputImagen4.Resolution;
}

export namespace InputImagen4 {
    /** Output aspect ratio. */
    export const AspectRatio = {
        Sixteen9: "16:9",
        Nine16: "9:16",
        Four3: "4:3",
        Three4: "3:4",
        One1: "1:1",
    } as const;
    export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];
    /** Output resolution. */
    export const Resolution = {
        OneK: "1K",
        TwoK: "2K",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
}
