// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `elevenlabs-multilingual-sts-v2`.
 */
export interface InputElevenlabsMultilingualStsV2 {
    /** Speech to re-voice. The delivery, pacing, and timing of this recording are preserved; only the voice changes. At most 104.8 MB. */
    audio: Hedra.InputElevenlabsMultilingualStsV2Audio;
    /** Voice to speak with (`voice_<uuid>`). List the library voices at GET /v3/models/elevenlabs-multilingual-sts-v2/voices, or use the voice a voice-clone job returned. */
    voice_id: string;
}
