// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `seedance-20`.
 *
 * Accepted field combinations (one per input mode):
 * (1) requires: aspect_ratio, duration_ms, prompt, resolution; accepts quality: standard
 * (2) requires: aspect_ratio, duration_ms, prompt, resolution; accepts quality: fast; resolution: 480p | 720p
 */
export interface InputSeedance20 {
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Generation prompt. */
    prompt: string;
    /** Output aspect ratio. */
    aspect_ratio: InputSeedance20.AspectRatio;
    /** Output resolution. */
    resolution: InputSeedance20.Resolution;
    /** Duration in ms. */
    duration_ms: number;
    /** Whether to generate native audio for the video. */
    generate_audio?: boolean | undefined;
    /** Start frame. From 300px to 6000px on each side, with an aspect ratio from 0.4 to 2.5, and at most 30 MB. */
    start_image?: Hedra.InputSeedance20StartImage | undefined;
    /** End frame. From 300px to 6000px on each side, with an aspect ratio from 0.4 to 2.5, and at most 30 MB. */
    end_image?: Hedra.InputSeedance20EndImage | undefined;
    /** Reference images. 1 to 9 images, each from 300px to 6000px on each side, with an aspect ratio from 0.4 to 2.5, and at most 30 MB. */
    images?: Hedra.InputSeedance20ImagesItem[] | undefined;
    /** Reference videos. 1 to 3 videos, each from 2s to 15s and at most 524.2 MB, at most 15s in total. */
    videos?: Hedra.InputSeedance20VideosItem[] | undefined;
    /** Reference audios. 1 to 3 audio files, each at most 104.8 MB, at most 15s in total. */
    audios?: Hedra.InputSeedance20AudiosItem[] | undefined;
    /** Quality level to generate at. `standard` — the full model, and the only level that reaches 1080p and 4K. `fast` — tuned for turnaround, at 480p and 720p. */
    quality?: InputSeedance20.Quality | undefined;
}

export namespace InputSeedance20 {
    /** Output aspect ratio. */
    export const AspectRatio = {
        One1: "1:1",
        Three4: "3:4",
        Four3: "4:3",
        Sixteen9: "16:9",
        TwentyOne9: "21:9",
        Nine16: "9:16",
        Adaptive: "adaptive",
    } as const;
    export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];
    /** Output resolution. */
    export const Resolution = {
        FourK: "4K",
        FourHundredEightyP: "480p",
        SevenHundredTwentyP: "720p",
        OneThousandEightyP: "1080p",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
    /** Quality level to generate at. `standard` — the full model, and the only level that reaches 1080p and 4K. `fast` — tuned for turnaround, at 480p and 720p. */
    export const Quality = {
        Standard: "standard",
        Fast: "fast",
    } as const;
    export type Quality = (typeof Quality)[keyof typeof Quality];
}
