// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `minimax-h3-max-turbo`.
 *
 * Accepted field combinations (one per input mode):
 * (1) requires: duration_ms, prompt, resolution, start_image; must omit: aspect_ratio, end_image
 * (2) requires: duration_ms, end_image, prompt, resolution, start_image; must omit: aspect_ratio
 * (3) requires: aspect_ratio, duration_ms, prompt, resolution; must omit: end_image, start_image
 */
export interface InputMinimaxH3MaxTurbo {
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Generation prompt. From 1 to 7000 characters. */
    prompt: string;
    /** Output resolution. */
    resolution: InputMinimaxH3MaxTurbo.Resolution;
    /** Duration in ms. */
    duration_ms: number;
    /** Start frame. From 256px to 5760px on each side, with an aspect ratio from 0.4 to 2.5, and at most 30 MB. */
    start_image?: Hedra.InputMinimaxH3MaxTurboStartImage | undefined;
    /** End frame. From 256px to 5760px on each side, with an aspect ratio from 0.4 to 2.5, and at most 30 MB. */
    end_image?: Hedra.InputMinimaxH3MaxTurboEndImage | undefined;
    /** Output aspect ratio. */
    aspect_ratio?: InputMinimaxH3MaxTurbo.AspectRatio | undefined;
}

export namespace InputMinimaxH3MaxTurbo {
    /** Output resolution. */
    export const Resolution = {
        FourHundredEightyP: "480p",
        SevenHundredSixtyEightP: "768p",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
    /** Output aspect ratio. */
    export const AspectRatio = {
        Three4: "3:4",
        Four3: "4:3",
        One1: "1:1",
        Nine16: "9:16",
        Sixteen9: "16:9",
        TwentyOne9: "21:9",
    } as const;
    export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];
}
