// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `kling-21-master`.
 */
export interface InputKling21Master {
    num_outputs?: number | undefined;
    /** Generation prompt. */
    prompt: string;
    /** Output aspect ratio. */
    aspect_ratio: InputKling21Master.AspectRatio;
    /** Output resolution. */
    resolution?: InputKling21Master.Resolution | undefined;
    /** Duration in ms. */
    duration_ms: number;
    /** Start frame (image-to-video). */
    start_image?: Hedra.InputKling21MasterStartImage | undefined;
    /** What to avoid in the generated video. */
    negative_prompt?: string | undefined;
    /** How closely the model follows the prompt. */
    cfg_scale?: number | undefined;
}

export namespace InputKling21Master {
    /** Output aspect ratio. */
    export const AspectRatio = {
        Sixteen9: "16:9",
        Nine16: "9:16",
        One1: "1:1",
    } as const;
    export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];
    /** Output resolution. */
    export const Resolution = {
        SevenHundredTwentyP: "720p",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
}
