// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `omnihuman-15`.
 */
export interface InputOmnihuman15 {
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Generation prompt. */
    prompt?: string | undefined;
    /** Output aspect ratio. */
    aspect_ratio?: InputOmnihuman15.AspectRatio | undefined;
    /** Output resolution. */
    resolution: InputOmnihuman15.Resolution;
    /** Start frame (image-to-video). At most 10.4 MB. */
    start_image: Hedra.InputOmnihuman15StartImage;
    /** Driving audio. At most 59.88s and at most 104.8 MB. */
    audio: Hedra.InputOmnihuman15Audio;
}

export namespace InputOmnihuman15 {
    /** Output aspect ratio. */
    export const AspectRatio = {
        Sixteen9: "16:9",
    } as const;
    export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];
    /** Output resolution. */
    export const Resolution = {
        SevenHundredTwentyP: "720p",
        OneThousandEightyP: "1080p",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
}
