// This file was auto-generated by Fern from our API Definition.

import * as Hedra from "../index.js";

/**
 * Model-specific inputs for `veed-fabric-10`.
 */
export interface InputVeedFabric10 {
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Generation prompt. */
    prompt: string;
    /** Output aspect ratio. */
    aspect_ratio: InputVeedFabric10.AspectRatio;
    /** Output resolution. */
    resolution: InputVeedFabric10.Resolution;
    /** Start frame (image-to-video). */
    start_image: Hedra.InputVeedFabric10StartImage;
    /** Driving audio. */
    audio: Hedra.InputVeedFabric10Audio;
}

export namespace InputVeedFabric10 {
    /** Output aspect ratio. */
    export const AspectRatio = {
            Sixteen9: "16:9",
            Nine16: "9:16",
            Four3: "4:3",
            Three4: "3:4",
            One1: "1:1"
        } as const;
    export type AspectRatio = typeof AspectRatio[keyof typeof AspectRatio];
    /** Output resolution. */
    export const Resolution = {
            FourHundredEightyP: "480p",
            SevenHundredTwentyP: "720p"
        } as const;
    export type Resolution = typeof Resolution[keyof typeof Resolution];
}
