// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `heygen-photo-avatar-4`.
 */
export interface InputHeygenPhotoAvatar4 {
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Generation prompt. */
    prompt?: string | undefined;
    /** Output aspect ratio. */
    aspect_ratio: InputHeygenPhotoAvatar4.AspectRatio;
    /** Output resolution. */
    resolution: InputHeygenPhotoAvatar4.Resolution;
    /** Start frame. At most 10.4 MB. */
    start_image: Hedra.InputHeygenPhotoAvatar4StartImage;
    /** Driving audio. At most 104.8 MB. */
    audio: Hedra.InputHeygenPhotoAvatar4Audio;
}

export namespace InputHeygenPhotoAvatar4 {
    /** Output aspect ratio. */
    export const AspectRatio = {
        Sixteen9: "16:9",
        Nine16: "9:16",
        Four5: "4:5",
        Five4: "5:4",
        One1: "1:1",
        Auto: "auto",
    } as const;
    export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];
    /** Output resolution. */
    export const Resolution = {
        ThreeHundredSixtyP: "360p",
        FourHundredEightyP: "480p",
        FiveHundredFortyP: "540p",
        SevenHundredTwentyP: "720p",
        OneThousandEightyP: "1080p",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
}
