// This file was auto-generated by Fern from our API Definition.

/**
 * Model-specific inputs for `ideogram-v4`.
 */
export interface InputIdeogramV4 {
    /** Generation prompt. */
    prompt: string;
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Rewrite the prompt before generation. An LLM expands it into a fuller description and the model receives that text instead of the submitted one; the result's `prompt` reports what ran. */
    enhance_prompt?: boolean | undefined;
    /** Output aspect ratio. */
    aspect_ratio: InputIdeogramV4.AspectRatio;
    /** Output resolution. */
    resolution: InputIdeogramV4.Resolution;
    /** Output image format. */
    output_format?: InputIdeogramV4.OutputFormat | undefined;
    /** Seed for reproducible output; omit for a random seed. */
    seed?: number | undefined;
    /** Quality level to generate at. */
    quality: InputIdeogramV4.Quality;
}

export namespace InputIdeogramV4 {
    /** Output aspect ratio. */
    export const AspectRatio = {
        Sixteen9: "16:9",
        Nine16: "9:16",
        Four3: "4:3",
        Three4: "3:4",
        One1: "1:1",
    } as const;
    export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];
    /** Output resolution. */
    export const Resolution = {
        SevenHundredTwentyP: "720p",
        OneThousandFourHundredFortyP2KQhd: "1440p (2K QHD)",
        TwoThousandOneHundredSixtyP4KUhd: "2160p (4K UHD)",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
    /** Output image format. */
    export const OutputFormat = {
        Jpeg: "jpeg",
        Png: "png",
    } as const;
    export type OutputFormat = (typeof OutputFormat)[keyof typeof OutputFormat];
    /** Quality level to generate at. */
    export const Quality = {
        Turbo: "turbo",
        Balanced: "balanced",
        Quality: "quality",
    } as const;
    export type Quality = (typeof Quality)[keyof typeof Quality];
}
