// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Model-specific inputs for `kling-25-turbo`.
 *
 * Accepted field combinations (one per input mode):
 * (1) requires: aspect_ratio, duration_ms, prompt; must omit: start_image
 * (2) requires: aspect_ratio, duration_ms, prompt, start_image
 */
export interface InputKling25Turbo {
    /** Number of outputs generated per job. Only 1 is supported. */
    num_outputs?: number | undefined;
    /** Generation prompt. */
    prompt: string;
    /** Output aspect ratio. */
    aspect_ratio: InputKling25Turbo.AspectRatio;
    /** Output resolution. */
    resolution?: InputKling25Turbo.Resolution | undefined;
    /** Duration in ms. */
    duration_ms: number;
    /** Start frame (image-to-video). */
    start_image?: Hedra.InputKling25TurboStartImage | undefined;
    /** What to avoid in the generated video. */
    negative_prompt?: string | undefined;
    /** How closely the model follows the prompt. */
    cfg_scale?: number | undefined;
}

export namespace InputKling25Turbo {
    /** Output aspect ratio. */
    export const AspectRatio = {
        Sixteen9: "16:9",
        Nine16: "9:16",
        One1: "1:1",
    } as const;
    export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];
    /** Output resolution. */
    export const Resolution = {
        OneThousandEightyP: "1080p",
    } as const;
    export type Resolution = (typeof Resolution)[keyof typeof Resolution];
}
