// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * One customer-visible lifecycle event for a v3 job.
 */
export interface JobLogItem {
    id: number;
    timestamp: string;
    level: Hedra.JobLogLevel;
    event: Hedra.JobLogEvent;
    message: string;
    source: Hedra.JobLogSource;
    data?: Record<string, unknown> | undefined;
}
