// This file was auto-generated by Fern from our API Definition.

export const JobLogSource = {
        Api: "api",
        Worker: "worker",
        Provider: "provider",
        Cron: "cron"
    } as const;
export type JobLogSource = typeof JobLogSource[keyof typeof JobLogSource];
