// This file was auto-generated by Fern from our API Definition.

export const JobLogLevel = {
        Info: "info",
        Warning: "warning",
        Error: "error"
    } as const;
export type JobLogLevel = typeof JobLogLevel[keyof typeof JobLogLevel];
