// This file was auto-generated by Fern from our API Definition.

/** The four states a job can be in. */
export const JobStatus = {
    InQueue: "IN_QUEUE",
    InProgress: "IN_PROGRESS",
    Completed: "COMPLETED",
    Failed: "FAILED",
} as const;
export type JobStatus = (typeof JobStatus)[keyof typeof JobStatus];
