// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

export interface JobSummary {
    job_id: string;
    model: string;
    /** The quality level this job ran at; present only for models that offer quality levels. */
    quality?: (string | null) | undefined;
    status: Hedra.JobStatus;
    created_at: string;
}
