// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

export interface KeyCreateResponse {
    key_id: string;
    credential: string;
    kind: Hedra.ApiKeyKind;
    name?: (string | null) | undefined;
    scopes?: (string[] | null) | undefined;
    workspace_id?: (string | null) | undefined;
    expires_at?: (string | null) | undefined;
    created_at?: (string | null) | undefined;
}
