// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

export interface KeySummary {
    key_id: string | null;
    kind: Hedra.ApiKeyKind;
    name?: (string | null) | undefined;
    scopes?: (string[] | null) | undefined;
    workspace_id?: (string | null) | undefined;
    status: Hedra.KeyStatus;
    created_at?: (string | null) | undefined;
    expires_at?: (string | null) | undefined;
    revoked_at?: (string | null) | undefined;
    last_used_at?: (string | null) | undefined;
}
