// This file was auto-generated by Fern from our API Definition.

/**
 * Price per one million tokens, in USD.
 */
export interface LlmPricing {
    usd_per_1m_input_tokens: number;
    usd_per_1m_output_tokens: number;
}
