// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * One chat-completion request's metering record.
 *
 * Metadata only: prompt and completion content are never retained, so there
 * is no content to expose — by construction, not by filtering.
 */
export interface LlmUsageRecord {
    /** The request's id — the same value the chat response returned in its `X-Request-Id` header. */
    id: string;
    /** The model id the request was admitted for. */
    model: string;
    /** `pending` while the request is in flight, `ok` once its usage settled, `upstream_error`/`client_abort`/`timeout` for requests that ended without a normal completion, and `settlement_failed` for delivered work whose usage could not be recorded in time — a later recovery may still fill in the amount. */
    status: Hedra.LlmUsageStatus;
    /** Whether the response was streamed. */
    streamed: boolean;
    /** Prompt tokens the request consumed; null until settled. */
    prompt_tokens: number | null;
    /** Completion tokens generated; null until settled. */
    completion_tokens: number | null;
    /** Reasoning tokens, as a breakdown of `completion_tokens` (never an addend); null when the model reports none. */
    reasoning_tokens: number | null;
    /** True when the token counts were estimated rather than reported by the model runtime. */
    usage_estimated: boolean;
    /** What this request cost; null until its usage settles. */
    cost: number | null;
    /** ISO-4217 currency code for `cost`. Present exactly when `cost` is. */
    currency: string | null;
    /** Milliseconds to first token; null when not measured. */
    ttft_ms: number | null;
    /** Total request duration in milliseconds; null while in flight. */
    duration_ms: number | null;
    /** `key_id` of the API key that made the request. Null for requests not attributable to a current key: session-token requests, requests whose key was since deleted, and legacy keys that predate public key ids. */
    key_id: string | null;
    /** The completion id (`id` in the chat response body), for correlating a record to a completion; null when the request did not yield a recordable one. */
    completion_id: string | null;
    /** ISO-8601 instant the request was admitted. */
    created_at: string;
    /** ISO-8601 instant the usage settled; null until then. */
    settled_at: string | null;
}
