// This file was auto-generated by Fern from our API Definition.

/**
 * Lifecycle of one chat-completion metering record. Same string values as
 * the stored rows (``db_models.llm_request.LlmRequestStatus``), re-declared
 * so the public OpenAPI publishes a surface-named component.
 */
export const LlmUsageStatus = {
    Pending: "pending",
    Ok: "ok",
    UpstreamError: "upstream_error",
    ClientAbort: "client_abort",
    Timeout: "timeout",
    SettlementFailed: "settlement_failed",
} as const;
export type LlmUsageStatus = (typeof LlmUsageStatus)[keyof typeof LlmUsageStatus];
