// This file was auto-generated by Fern from our API Definition.

/** Wire encoding for one log drain endpoint's HTTP posts. */
export const LogDrainFormat = {
    Ndjson: "ndjson",
    Otlp: "otlp",
} as const;
export type LogDrainFormat = (typeof LogDrainFormat)[keyof typeof LogDrainFormat];
