// This file was auto-generated by Fern from our API Definition.

export interface LogDrainTestResponse {
    ok: boolean;
    response_status?: (number | null) | undefined;
    error?: (string | null) | undefined;
}
