// This file was auto-generated by Fern from our API Definition.

export interface ModelSummary {
    id: string;
    modality: string;
    name?: (string | null) | undefined;
    description?: (string | null) | undefined;
    thumbnail_url?: (string | null) | undefined;
    premium?: (boolean | null) | undefined;
}
