// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

export interface ModelDetail {
    /** The model's public id — the value POST /v3/models/{model} takes. */
    id: string;
    modality: Hedra.Modality;
    /** Human-readable name. */
    name?: (string | null) | undefined;
    /** One-line summary of what the model does. */
    description?: (string | null) | undefined;
    /** Short USD pricing summary for this model. Exact cost depends on input. */
    price_description?: string | undefined;
    /** URL of the provider's logo. */
    logo_url?: (string | null) | undefined;
    /** A chat model's context window in tokens; null for other models. */
    context_length?: (number | null) | undefined;
    /** The largest `max_tokens` a chat model accepts; null for other models. */
    max_output_tokens?: (number | null) | undefined;
    /** JSON Schema for this model's `input` object on submit — the same schema `GET /v3/models/{model}/openapi.json` embeds. For a chat model, the JSON Schema of the `POST /v3/chat/completions` request body as this model accepts it; a chat model has no per-model OpenAPI document. */
    input_schema?: Record<string, unknown> | undefined;
    /** JSON Schema of one item of a completed job's `outputs[]`. Empty for a chat model. */
    output_schema?: Record<string, unknown> | undefined;
    /** The facts about a chat model that its `input_schema` cannot state: token prices, the default output bound and the image limit; null for other models. */
    chat?: (Hedra.ChatCapabilities | null) | undefined;
}
