// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

export interface ModelSummary {
    /** The model's public id — the value POST /v3/models/{model} takes. */
    id: string;
    modality: Hedra.Modality;
    /** Human-readable name. */
    name?: (string | null) | undefined;
    /** One-line summary of what the model does. */
    description?: (string | null) | undefined;
    /** Short USD pricing summary for this model. Exact cost depends on input. */
    price_description?: string | undefined;
    /** URL of the provider's logo. */
    logo_url?: (string | null) | undefined;
    /** A chat model's context window in tokens; null for other models. */
    context_length?: (number | null) | undefined;
    /** The largest `max_tokens` a chat model accepts; null for other models. */
    max_output_tokens?: (number | null) | undefined;
}
