// This file was auto-generated by Fern from our API Definition.

/**
 * The OpenAI error object — this surface's dialect, not the v3 envelope.
 */
export interface OpenAiError {
    message: string;
    type: string;
    param?: (string | null) | undefined;
    code?: (string | null) | undefined;
}
