// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * One item of a job's `outputs[]` (`GET /v3/jobs/{job_id}`). `outputs` is
 * always an array, even for a single output.
 *
 * Every key is always present. The ones a modality carries no value for
 * serialize as null — an image output reports `duration_ms: null` and
 * `fps: null`, an audio output `width: null` — so the shape is one object
 * rather than one per modality.
 */
export interface OutputItem {
    status?: Hedra.OutputStatus | undefined;
    url?: (string | null) | undefined;
    content_type?: (string | null) | undefined;
    width?: (number | null) | undefined;
    height?: (number | null) | undefined;
    duration_ms?: (number | null) | undefined;
    fps?: (number | null) | undefined;
    error?: (Hedra.ErrorEnvelope | null) | undefined;
}
