// This file was auto-generated by Fern from our API Definition.

/**
 * Extensible pricing information for AI models.
 *
 * Price is calculated as:
 *     credits = ceil((base_cost + credits_per_second * duration_seconds) * product(modifiers))
 *
 * For video models (per-second billing):
 *     - base_cost is typically 0
 *     - credits_per_second is the per-second rate
 *     - duration_seconds is the video length
 *     - modifiers adjust for resolution, audio generation, etc.
 *
 * For image models (per-generation billing):
 *     - base_cost is the flat cost per generation (e.g., 5 credits)
 *     - credits_per_second is 0
 *     - duration_seconds is ignored (or 0)
 *     - modifiers can still adjust for resolution, style, etc.
 *
 * Modifiers are only included when they affect pricing (i.e., non-1.0 values).
 */
export interface Pricing {
    /** Flat base cost in credits. Present for per-generation models (images). Duration-based models leave this unset. */
    base_cost?: (number | null) | undefined;
    /** Credit cost per second. Only present for duration-based models. Image/per-generation models leave this unset. */
    credits_per_second?: (number | null) | undefined;
    /** Pricing modifiers by dimension. Each dimension (e.g. 'resolution', 'generate_audio') maps option values to their price multipliers. Only non-1.0 modifiers are included (1.0 is the implicit default). Example: {'resolution': {'540p': 0.5, '1080p': 3.0}} */
    modifiers?: Record<string, Record<string, number>> | undefined;
}
