// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

export interface RequestListResponse {
    data?: Hedra.RequestSummary[] | undefined;
    next_cursor?: (string | null) | undefined;
}
