// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

export interface StatusResponse {
    request_id: string;
    status: Hedra.RequestStatus;
    progress?: (number | null) | undefined;
    estimated_completion_at?: (string | null) | undefined;
    logs?: Hedra.StatusLog[] | undefined;
}
