// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

/**
 * Body of a `billing.top_off_failed` webhook.
 *
 * Hedra sends this event when Stripe declines the payment method for an
 * automatic top-up of the API wallet. After a decline, Hedra holds further
 * automatic top-ups until the hold expires, the payment method changes or a
 * top-up is paid, and sends no event for a decline while a hold is in place.
 */
export interface TopOffFailedEvent {
    /** The event's id, the same value as `X-Hedra-Webhook-Id`. */
    id: string;
    /** Always `billing.top_off_failed`. */
    type: Hedra.BillingEventType;
    /** When the top-up was declined. */
    created_at: string;
    reason: Hedra.TopOffFailureReason;
    /** The amount the top-up tried to add. */
    amount_attempted: number;
    /** The API wallet's balance when this event was sent. */
    balance: number;
    /** ISO-4217 currency code for every amount in this event. */
    currency: string;
}
