// This file was auto-generated by Fern from our API Definition.

/**
 * One movement of the API wallet's balance.
 */
export interface TransactionRecord {
    /** The transaction's id. Stable, and the same id the V2 billing history reports for this row. */
    id: string;
    /** What moved the balance: `purchase` when funds were bought, `grant` when they were granted by a plan entitlement, `usage` when a job was charged, `refund` when a charge was returned, `adjustment` when Hedra corrected the balance, and `other` for a movement this API version does not yet name. The list is open and may gain values, so switch on it with a default branch; `amount` is authoritative for a kind you do not recognize. */
    kind: string;
    /** The change to the balance, signed: negative for a charge, positive for funds arriving. Null for a row written before the wallet recorded amounts, whose movement is unknown rather than zero; no such row exists in production. */
    amount: number | null;
    /** ISO-4217 currency code for `amount`; null exactly when `amount` is. */
    currency: string | null;
    /** ISO-8601 instant the balance moved. */
    created_at: string;
}
