// This file was auto-generated by Fern from our API Definition.

/**
 * One usage rollup row. `key` is ``"total"`` for the summary, an ISO date
 * (``YYYY-MM-DD``, UTC) for ``group_by=day``, or a public model id for
 * ``group_by=model``.
 */
export interface UsageBucket {
    key: string;
    jobs: number;
    /** Net amount spent in this bucket. */
    spent: number;
}
