// This file was auto-generated by Fern from our API Definition.

import * as Hedra from "../index.js";

export interface VoiceListResponse {
    /** This page of items. */
    data: Hedra.VoiceSummary[];
    /** Opaque cursor for the next page, or null when this response completes the list. Always present. Endpoints that serve the whole collection at once always return null. */
    next_cursor: string | null;
}
