// This file was auto-generated by Fern from our API Definition.

export interface WebhookDefaultConfig {
    /** The stored default endpoint; null when none is configured. */
    url?: (string | null) | undefined;
    /** Whether the default endpoint is active. */
    enabled?: boolean | undefined;
    /** ISO-8601 instant the config last changed. */
    updated_at?: (string | null) | undefined;
    /** The API key that last changed the config. */
    updated_by_key_id?: (string | null) | undefined;
}
