// This file was auto-generated by Fern from our API Definition.

/**
 * The ed25519 public key callers verify outbound webhook signatures with.
 */
export interface WebhookPublicKey {
    algorithm?: string | undefined;
    public_key: string;
}
