// This file was auto-generated by Fern from our API Definition.

export interface WebhookDefaultConfig {
    url?: (string | null) | undefined;
    enabled?: boolean | undefined;
    updated_at?: (string | null) | undefined;
    updated_by_key_id?: (string | null) | undefined;
}
