// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../index.js";

export interface WebhookDeliverySummary {
    job_id: string;
    job_accessible: boolean;
    model: string;
    event_type?: (Hedra.WebhookEventType | null) | undefined;
    status: Hedra.WebhookDeliveryStatus;
    source: Hedra.WebhookDeliverySource;
    attempts: number;
    redelivery_count?: number | undefined;
    redeliveries?: Hedra.WebhookRedelivery[] | undefined;
    last_response_status?: (number | null) | undefined;
    /** Why the most recent delivery attempt failed, in the same error envelope `GET /jobs/{job_id}` returns for a failed job: a stable `code` from the shared error vocabulary, a fixed operator-facing `message`, and `retryable`. Null while no attempt has failed. Destination URLs, addresses, headers, credentials, response bodies, and internal exception text are never included — those stay in Hedra's own logs. `retryable` describes the condition, not what Hedra did: every non-2xx response is retried on the published ladder, so it answers whether replaying this delivery is likely to help. Deliveries that failed before this field became structured report `UNKNOWN`. */
    last_error?: (Hedra.ErrorEnvelope | null) | undefined;
    webhook_url: string;
    created_at: string;
    last_attempt_at?: (string | null) | undefined;
}
