// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../../index.js";

/**
 * @example
 *     {}
 */
export interface ListGenerationsRequest {
    type?: Hedra.ListGenerationsRequestType | null;
    created_before?: string | null;
    created_after?: string | null;
    prompt_query?: string | null;
    agent_thread_id?: string | null;
    ids?: string | null;
    /** Number of items returned in the page. */
    limit?: number;
    /** Number of records skipped. */
    offset?: number;
}
