// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface KeyRotateRequest {
    /** Seconds the old secret keeps authenticating after the rotation; omitted means the service default (24h). */
    grace_period_seconds?: number | null;
}
