// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Hedra from "../../../index.js";

export declare namespace KeysClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class KeysClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<KeysClient.Options>;

    constructor(options: KeysClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {Hedra.KeysListRequest} request
     * @param {KeysClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Hedra.BadRequestError}
     * @throws {@link Hedra.UnauthorizedError}
     * @throws {@link Hedra.ForbiddenError}
     * @throws {@link Hedra.NotFoundError}
     * @throws {@link Hedra.TooManyRequestsError}
     * @throws {@link Hedra.InternalServerError}
     * @throws {@link errors.HedraError}
     * @throws {@link errors.HedraTimeoutError}
     *
     * @example
     *     await client.keys.list()
     */
    public list(
        request: Hedra.KeysListRequest = {},
        requestOptions?: KeysClient.RequestOptions,
    ): core.HttpResponsePromise<Hedra.KeyListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: Hedra.KeysListRequest = {},
        requestOptions?: KeysClient.RequestOptions,
    ): Promise<core.WithRawResponse<Hedra.KeyListResponse>> {
        const { workspace_id: workspaceId } = request;
        const _queryParams: Record<string, unknown> = {
            workspace_id: workspaceId,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Hedra-Spec-Version": requestOptions?.specVersion ?? "3.3.0" }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.HedraEnvironment.Production,
                "keys",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Hedra.KeyListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Hedra.BadRequestError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 401:
                    throw new Hedra.UnauthorizedError(
                        _response.error.body as Hedra.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Hedra.ForbiddenError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 404:
                    throw new Hedra.NotFoundError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Hedra.TooManyRequestsError(
                        _response.error.body as Hedra.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Hedra.InternalServerError(
                        _response.error.body as Hedra.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.HedraError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/keys");
    }

    /**
     * @param {Hedra.KeyCreateRequest} request
     * @param {KeysClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Hedra.BadRequestError}
     * @throws {@link Hedra.UnauthorizedError}
     * @throws {@link Hedra.ForbiddenError}
     * @throws {@link Hedra.NotFoundError}
     * @throws {@link Hedra.TooManyRequestsError}
     * @throws {@link Hedra.InternalServerError}
     * @throws {@link errors.HedraError}
     * @throws {@link errors.HedraTimeoutError}
     *
     * @example
     *     await client.keys.create()
     */
    public create(
        request: Hedra.KeyCreateRequest = {},
        requestOptions?: KeysClient.RequestOptions,
    ): core.HttpResponsePromise<Hedra.KeyCreateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: Hedra.KeyCreateRequest = {},
        requestOptions?: KeysClient.RequestOptions,
    ): Promise<core.WithRawResponse<Hedra.KeyCreateResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Hedra-Spec-Version": requestOptions?.specVersion ?? "3.3.0" }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.HedraEnvironment.Production,
                "keys",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Hedra.KeyCreateResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Hedra.BadRequestError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 401:
                    throw new Hedra.UnauthorizedError(
                        _response.error.body as Hedra.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Hedra.ForbiddenError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 404:
                    throw new Hedra.NotFoundError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Hedra.TooManyRequestsError(
                        _response.error.body as Hedra.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Hedra.InternalServerError(
                        _response.error.body as Hedra.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.HedraError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/keys");
    }

    /**
     * @param {string} key_id - The key's public identifier.
     * @param {Hedra.KeyRotateRequest} request
     * @param {KeysClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Hedra.BadRequestError}
     * @throws {@link Hedra.UnauthorizedError}
     * @throws {@link Hedra.ForbiddenError}
     * @throws {@link Hedra.NotFoundError}
     * @throws {@link Hedra.TooManyRequestsError}
     * @throws {@link Hedra.InternalServerError}
     * @throws {@link errors.HedraError}
     * @throws {@link errors.HedraTimeoutError}
     *
     * @example
     *     await client.keys.rotate("key_id")
     */
    public rotate(
        key_id: string,
        request: Hedra.KeyRotateRequest = {},
        requestOptions?: KeysClient.RequestOptions,
    ): core.HttpResponsePromise<Hedra.KeyRotateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__rotate(key_id, request, requestOptions));
    }

    private async __rotate(
        key_id: string,
        request: Hedra.KeyRotateRequest = {},
        requestOptions?: KeysClient.RequestOptions,
    ): Promise<core.WithRawResponse<Hedra.KeyRotateResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Hedra-Spec-Version": requestOptions?.specVersion ?? "3.3.0" }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.HedraEnvironment.Production,
                `keys/${core.url.encodePathParam(key_id)}/rotate`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Hedra.KeyRotateResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Hedra.BadRequestError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 401:
                    throw new Hedra.UnauthorizedError(
                        _response.error.body as Hedra.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Hedra.ForbiddenError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 404:
                    throw new Hedra.NotFoundError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Hedra.TooManyRequestsError(
                        _response.error.body as Hedra.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Hedra.InternalServerError(
                        _response.error.body as Hedra.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.HedraError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/keys/{key_id}/rotate");
    }

    /**
     * @param {string} key_id - The key's public identifier.
     * @param {Hedra.KeysRevokeRequest} request
     * @param {KeysClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Hedra.BadRequestError}
     * @throws {@link Hedra.UnauthorizedError}
     * @throws {@link Hedra.ForbiddenError}
     * @throws {@link Hedra.NotFoundError}
     * @throws {@link Hedra.TooManyRequestsError}
     * @throws {@link Hedra.InternalServerError}
     * @throws {@link errors.HedraError}
     * @throws {@link errors.HedraTimeoutError}
     *
     * @example
     *     await client.keys.revoke("key_id")
     */
    public revoke(
        key_id: string,
        request: Hedra.KeysRevokeRequest = {},
        requestOptions?: KeysClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__revoke(key_id, request, requestOptions));
    }

    private async __revoke(
        key_id: string,
        _request: Hedra.KeysRevokeRequest = {},
        requestOptions?: KeysClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Hedra-Spec-Version": requestOptions?.specVersion ?? "3.3.0" }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.HedraEnvironment.Production,
                `keys/${core.url.encodePathParam(key_id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Hedra.BadRequestError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 401:
                    throw new Hedra.UnauthorizedError(
                        _response.error.body as Hedra.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Hedra.ForbiddenError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 404:
                    throw new Hedra.NotFoundError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Hedra.TooManyRequestsError(
                        _response.error.body as Hedra.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Hedra.InternalServerError(
                        _response.error.body as Hedra.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.HedraError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/keys/{key_id}");
    }
}
