// This file was auto-generated by Fern from our API Definition.

import * as Hedra from "../../src/api/index";
import { HedraClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ChatClient", () => {
    test("completionsCreate (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().post("/chat/completions").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.chat.completionsCreate();
        expect(response).toEqual(rawResponseBody);
    });

    test("completionsCreate (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().post("/chat/completions").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.chat.completionsCreate();
        }).rejects.toThrow(Hedra.BadRequestError);
    });

    test("completionsCreate (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().post("/chat/completions").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.chat.completionsCreate();
        }).rejects.toThrow(Hedra.UnauthorizedError);
    });

    test("completionsCreate (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().post("/chat/completions").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.chat.completionsCreate();
        }).rejects.toThrow(Hedra.PaymentRequiredError);
    });

    test("completionsCreate (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().post("/chat/completions").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.chat.completionsCreate();
        }).rejects.toThrow(Hedra.ForbiddenError);
    });

    test("completionsCreate (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().post("/chat/completions").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.chat.completionsCreate();
        }).rejects.toThrow(Hedra.NotFoundError);
    });

    test("completionsCreate (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().post("/chat/completions").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.chat.completionsCreate();
        }).rejects.toThrow(Hedra.TooManyRequestsError);
    });

    test("completionsCreate (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().post("/chat/completions").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.chat.completionsCreate();
        }).rejects.toThrow(Hedra.InternalServerError);
    });

    test("completionsCreate (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { message: "message", type: "type" } };

        server.mockEndpoint().post("/chat/completions").respondWith().statusCode(502).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.chat.completionsCreate();
        }).rejects.toThrow(Hedra.BadGatewayError);
    });

    test("completionsCreate (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { message: "message", type: "type" } };

        server.mockEndpoint().post("/chat/completions").respondWith().statusCode(503).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.chat.completionsCreate();
        }).rejects.toThrow(Hedra.ServiceUnavailableError);
    });

    test("completionsCreate (11)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { message: "message", type: "type" } };

        server.mockEndpoint().post("/chat/completions").respondWith().statusCode(504).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.chat.completionsCreate();
        }).rejects.toThrow(Hedra.GatewayTimeoutError);
    });

    test("llms_list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            object: "list",
            data: [
                {
                    id: "id",
                    object: "model",
                    created: 1,
                    owned_by: "owned_by",
                    name: "name",
                    description: "description",
                    context_length: 1,
                    max_output_tokens: 1,
                    capabilities: { tools: true, response_format: true, vision: true, reasoning: true },
                    pricing: { usd_per_1m_input_tokens: 1.1, usd_per_1m_output_tokens: 1.1 },
                },
            ],
        };

        server.mockEndpoint().get("/llms").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.chat.llmsList();
        expect(response).toEqual(rawResponseBody);
    });

    test("llms_list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/llms").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.chat.llmsList();
        }).rejects.toThrow(Hedra.BadRequestError);
    });

    test("llms_list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/llms").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.chat.llmsList();
        }).rejects.toThrow(Hedra.NotFoundError);
    });

    test("llms_list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/llms").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.chat.llmsList();
        }).rejects.toThrow(Hedra.InternalServerError);
    });

    test("llms_get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            object: "model",
            created: 1,
            owned_by: "owned_by",
            name: "name",
            description: "description",
            context_length: 1,
            max_output_tokens: 1,
            capabilities: { tools: true, response_format: true, vision: true, reasoning: true },
            pricing: { usd_per_1m_input_tokens: 1.1, usd_per_1m_output_tokens: 1.1 },
        };

        server.mockEndpoint().get("/llms/model").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.chat.llmsGet("model");
        expect(response).toEqual(rawResponseBody);
    });

    test("llms_get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/llms/model").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.chat.llmsGet("model");
        }).rejects.toThrow(Hedra.BadRequestError);
    });

    test("llms_get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/llms/model").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.chat.llmsGet("model");
        }).rejects.toThrow(Hedra.NotFoundError);
    });

    test("llms_get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/llms/model").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.chat.llmsGet("model");
        }).rejects.toThrow(Hedra.InternalServerError);
    });
});
