// This file was auto-generated by Fern from our API Definition.

import * as Hedra from "../../src/api/index";
import { HedraClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("JobsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    job_id: "job_id",
                    model: "model",
                    quality: "quality",
                    status: "IN_QUEUE",
                    created_at: "2024-01-15T09:30:00Z",
                },
            ],
            next_cursor: "next_cursor",
        };

        server
            .mockEndpoint({ once: false })
            .get("/jobs")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.jobs.list();

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/jobs").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.list();
        }).rejects.toThrow(Hedra.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/jobs").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.list();
        }).rejects.toThrow(Hedra.UnauthorizedError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/jobs").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.list();
        }).rejects.toThrow(Hedra.ForbiddenError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/jobs").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.list();
        }).rejects.toThrow(Hedra.NotFoundError);
    });

    test("list (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/jobs").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.list();
        }).rejects.toThrow(Hedra.TooManyRequestsError);
    });

    test("list (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/jobs").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.list();
        }).rejects.toThrow(Hedra.InternalServerError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            job_id: "job_id",
            model: "model",
            quality: "quality",
            status: "IN_QUEUE",
            prompt: "prompt",
            outputs: [
                {
                    status: "COMPLETED",
                    asset_id: "asset_id",
                    voice_id: "voice_id",
                    url: "url",
                    content_type: "content_type",
                    width: 1,
                    height: 1,
                    duration_ms: 1,
                    fps: 1,
                    error: { code: "UNKNOWN", message: "message" },
                },
            ],
            metrics: { processing_time_ms: 1, time_to_first_token_ms: 1 },
            usage: { prompt_tokens: 1, completion_tokens: 1, reasoning_tokens: 1, estimated: true },
            error: {
                code: "UNKNOWN",
                message: "message",
                retryable: true,
                retry_after: 1,
                param: "param",
                details: [{ field: "field", message: "message" }],
                replaced_by: "replaced_by",
                billing: {
                    balance: 1.1,
                    required: 1.1,
                    currency: "currency",
                    funding_url: "funding_url",
                    reason: "reason",
                },
                type: "invalid_request_error",
            },
            logs: [
                {
                    id: 1,
                    timestamp: "2024-01-15T09:30:00Z",
                    level: "info",
                    event: "queued",
                    message: "message",
                    source: "api",
                    data: { key: "value" },
                },
            ],
            cost: 1.1,
            currency: "currency",
        };

        server.mockEndpoint().get("/jobs/job_id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.jobs.get("job_id");
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/jobs/job_id").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.get("job_id");
        }).rejects.toThrow(Hedra.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/jobs/job_id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.get("job_id");
        }).rejects.toThrow(Hedra.UnauthorizedError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/jobs/job_id").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.get("job_id");
        }).rejects.toThrow(Hedra.ForbiddenError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/jobs/job_id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.get("job_id");
        }).rejects.toThrow(Hedra.NotFoundError);
    });

    test("get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/jobs/job_id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.get("job_id");
        }).rejects.toThrow(Hedra.TooManyRequestsError);
    });

    test("get (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/jobs/job_id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.get("job_id");
        }).rejects.toThrow(Hedra.InternalServerError);
    });

    test("getStatus (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            job_id: "job_id",
            status: "IN_QUEUE",
            progress: 1.1,
            estimated_completion_at: "2024-01-15T09:30:00Z",
            logs: [
                {
                    id: 1,
                    timestamp: "2024-01-15T09:30:00Z",
                    level: "info",
                    event: "queued",
                    message: "message",
                    source: "api",
                    data: { key: "value" },
                },
            ],
            logs_next_cursor: "logs_next_cursor",
        };

        server
            .mockEndpoint()
            .get("/jobs/job_id/status")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.jobs.getStatus("job_id");
        expect(response).toEqual(rawResponseBody);
    });

    test("getStatus (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .get("/jobs/job_id/status")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.getStatus("job_id");
        }).rejects.toThrow(Hedra.BadRequestError);
    });

    test("getStatus (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .get("/jobs/job_id/status")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.getStatus("job_id");
        }).rejects.toThrow(Hedra.UnauthorizedError);
    });

    test("getStatus (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .get("/jobs/job_id/status")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.getStatus("job_id");
        }).rejects.toThrow(Hedra.ForbiddenError);
    });

    test("getStatus (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .get("/jobs/job_id/status")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.getStatus("job_id");
        }).rejects.toThrow(Hedra.NotFoundError);
    });

    test("getStatus (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .get("/jobs/job_id/status")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.getStatus("job_id");
        }).rejects.toThrow(Hedra.TooManyRequestsError);
    });

    test("getStatus (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .get("/jobs/job_id/status")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.getStatus("job_id");
        }).rejects.toThrow(Hedra.InternalServerError);
    });

    test("listJobLogs (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: 1,
                    timestamp: "2024-01-15T09:30:00Z",
                    level: "info",
                    event: "queued",
                    message: "message",
                    source: "api",
                    data: { key: "value" },
                },
            ],
            next_cursor: "next_cursor",
        };

        server
            .mockEndpoint({ once: false })
            .get("/jobs/job_id/logs")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.jobs.listJobLogs("job_id");

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("listJobLogs (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/jobs/job_id/logs").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.listJobLogs("job_id");
        }).rejects.toThrow(Hedra.BadRequestError);
    });

    test("listJobLogs (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/jobs/job_id/logs").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.listJobLogs("job_id");
        }).rejects.toThrow(Hedra.UnauthorizedError);
    });

    test("listJobLogs (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/jobs/job_id/logs").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.listJobLogs("job_id");
        }).rejects.toThrow(Hedra.ForbiddenError);
    });

    test("listJobLogs (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/jobs/job_id/logs").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.listJobLogs("job_id");
        }).rejects.toThrow(Hedra.NotFoundError);
    });

    test("listJobLogs (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/jobs/job_id/logs").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.listJobLogs("job_id");
        }).rejects.toThrow(Hedra.TooManyRequestsError);
    });

    test("listJobLogs (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/jobs/job_id/logs").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.listJobLogs("job_id");
        }).rejects.toThrow(Hedra.InternalServerError);
    });

    test("stream (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody =
            'event: \ndata: {"job_id":"job_id","status":"IN_QUEUE","progress":1.1,"estimated_completion_at":"2024-01-15T09:30:00Z","logs":[{"id":1,"timestamp":"2024-01-15T09:30:00Z","level":"info","event":"queued","message":"message","source":"api","data":{"key":"value"}}],"logs_next_cursor":"logs_next_cursor"}\n\n';

        server.mockEndpoint().get("/jobs/job_id/stream").respondWith().statusCode(200).sseBody(rawResponseBody).build();

        const response = await client.jobs.stream("job_id");
        const events: unknown[] = [];
        for await (const event of response) {
            events.push(event);
        }
        expect(events).toEqual([
            {
                job_id: "job_id",
                status: "IN_QUEUE",
                progress: 1.1,
                estimated_completion_at: "2024-01-15T09:30:00Z",
                logs: [
                    {
                        id: 1,
                        timestamp: "2024-01-15T09:30:00Z",
                        level: "info",
                        event: "queued",
                        message: "message",
                        source: "api",
                        data: {
                            key: "value",
                        },
                    },
                ],
                logs_next_cursor: "logs_next_cursor",
            },
        ]);
    });

    test("stream (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .get("/jobs/job_id/stream")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.stream("job_id");
        }).rejects.toThrow(Hedra.BadRequestError);
    });

    test("stream (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .get("/jobs/job_id/stream")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.stream("job_id");
        }).rejects.toThrow(Hedra.UnauthorizedError);
    });

    test("stream (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .get("/jobs/job_id/stream")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.stream("job_id");
        }).rejects.toThrow(Hedra.ForbiddenError);
    });

    test("stream (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .get("/jobs/job_id/stream")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.stream("job_id");
        }).rejects.toThrow(Hedra.NotFoundError);
    });

    test("stream (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .get("/jobs/job_id/stream")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.stream("job_id");
        }).rejects.toThrow(Hedra.TooManyRequestsError);
    });

    test("stream (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .get("/jobs/job_id/stream")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.stream("job_id");
        }).rejects.toThrow(Hedra.InternalServerError);
    });
});
