// This file was auto-generated by Fern from our API Definition.

import * as Hedra from "../../src/api/index";
import { HedraClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("KeysClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    key_id: "key_id",
                    kind: "personal",
                    name: "name",
                    scopes: ["scopes"],
                    workspace_id: "workspace_id",
                    status: "active",
                    created_at: "created_at",
                    expires_at: "expires_at",
                    revoked_at: "revoked_at",
                    last_used_at: "last_used_at",
                },
            ],
            next_cursor: "next_cursor",
        };

        server.mockEndpoint().get("/keys").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.keys.list();
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/keys").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.keys.list();
        }).rejects.toThrow(Hedra.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/keys").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.keys.list();
        }).rejects.toThrow(Hedra.UnauthorizedError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/keys").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.keys.list();
        }).rejects.toThrow(Hedra.ForbiddenError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/keys").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.keys.list();
        }).rejects.toThrow(Hedra.NotFoundError);
    });

    test("list (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/keys").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.keys.list();
        }).rejects.toThrow(Hedra.UnprocessableEntityError);
    });

    test("list (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/keys").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.keys.list();
        }).rejects.toThrow(Hedra.TooManyRequestsError);
    });

    test("list (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/keys").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.keys.list();
        }).rejects.toThrow(Hedra.InternalServerError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            key_id: "key_id",
            credential: "credential",
            kind: "personal",
            name: "name",
            scopes: ["scopes"],
            workspace_id: "workspace_id",
            expires_at: "expires_at",
            created_at: "created_at",
        };

        server
            .mockEndpoint()
            .post("/keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.keys.create();
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .post("/keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.keys.create();
        }).rejects.toThrow(Hedra.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .post("/keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.keys.create();
        }).rejects.toThrow(Hedra.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .post("/keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.keys.create();
        }).rejects.toThrow(Hedra.ForbiddenError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .post("/keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.keys.create();
        }).rejects.toThrow(Hedra.NotFoundError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.keys.create();
        }).rejects.toThrow(Hedra.UnprocessableEntityError);
    });

    test("create (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .post("/keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.keys.create();
        }).rejects.toThrow(Hedra.TooManyRequestsError);
    });

    test("create (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .post("/keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.keys.create();
        }).rejects.toThrow(Hedra.InternalServerError);
    });

    test("rotate (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            key_id: "key_id",
            credential: "credential",
            kind: "personal",
            name: "name",
            scopes: ["scopes"],
            workspace_id: "workspace_id",
            expires_at: "expires_at",
            previous_secret_expires_at: "previous_secret_expires_at",
        };

        server
            .mockEndpoint()
            .post("/keys/key_id/rotate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.keys.rotate("key_id");
        expect(response).toEqual(rawResponseBody);
    });

    test("rotate (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .post("/keys/key_id/rotate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.keys.rotate("key_id");
        }).rejects.toThrow(Hedra.BadRequestError);
    });

    test("rotate (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .post("/keys/key_id/rotate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.keys.rotate("key_id");
        }).rejects.toThrow(Hedra.UnauthorizedError);
    });

    test("rotate (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .post("/keys/key_id/rotate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.keys.rotate("key_id");
        }).rejects.toThrow(Hedra.ForbiddenError);
    });

    test("rotate (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .post("/keys/key_id/rotate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.keys.rotate("key_id");
        }).rejects.toThrow(Hedra.NotFoundError);
    });

    test("rotate (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/keys/key_id/rotate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.keys.rotate("key_id");
        }).rejects.toThrow(Hedra.UnprocessableEntityError);
    });

    test("rotate (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .post("/keys/key_id/rotate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.keys.rotate("key_id");
        }).rejects.toThrow(Hedra.TooManyRequestsError);
    });

    test("rotate (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .post("/keys/key_id/rotate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.keys.rotate("key_id");
        }).rejects.toThrow(Hedra.InternalServerError);
    });

    test("revoke (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/keys/key_id").respondWith().statusCode(200).build();

        const response = await client.keys.revoke("key_id");
        expect(response).toEqual(undefined);
    });

    test("revoke (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().delete("/keys/key_id").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.keys.revoke("key_id");
        }).rejects.toThrow(Hedra.BadRequestError);
    });

    test("revoke (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().delete("/keys/key_id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.keys.revoke("key_id");
        }).rejects.toThrow(Hedra.UnauthorizedError);
    });

    test("revoke (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().delete("/keys/key_id").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.keys.revoke("key_id");
        }).rejects.toThrow(Hedra.ForbiddenError);
    });

    test("revoke (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().delete("/keys/key_id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.keys.revoke("key_id");
        }).rejects.toThrow(Hedra.NotFoundError);
    });

    test("revoke (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().delete("/keys/key_id").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.keys.revoke("key_id");
        }).rejects.toThrow(Hedra.UnprocessableEntityError);
    });

    test("revoke (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().delete("/keys/key_id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.keys.revoke("key_id");
        }).rejects.toThrow(Hedra.TooManyRequestsError);
    });

    test("revoke (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().delete("/keys/key_id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.keys.revoke("key_id");
        }).rejects.toThrow(Hedra.InternalServerError);
    });
});
