// This file was auto-generated by Fern from our API Definition.

import * as Hedra from "../../src/api/index";
import { HedraClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("HedraClient", () => {
    test("list_models (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                id: "id",
                name: "name",
                description: "description",
                type: "type",
                aspect_ratios: ["aspect_ratios"],
                resolutions: ["resolutions"],
                durations: ["durations"],
                requires_start_frame: true,
                requires_end_frame: true,
                requires_audio_input: true,
                requires_input_video: true,
                requires_character_orientation: true,
                max_duration_ms: 1,
                custom_resolution: true,
                price_details: { credit_cost: 1, unit_scale: 1, billing_unit: "billing_unit" },
                pricing: { base_cost: 1, credits_per_second: 1, modifiers: { key: { key: 1.1 } } },
                dimensions: { key: {} },
                logo_url: "logo_url",
                premium: true,
                display_order: 1,
            },
        ];

        server.mockEndpoint().get("/models").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.listModels();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_models (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/models").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.listModels();
        }).rejects.toThrow(Hedra.UnprocessableEntityError);
    });

    test("list_voices", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                id: "id",
                type: "text",
                name: "name",
                thumbnail_url: "thumbnail_url",
                description: "description",
                is_favorite: true,
                recent: true,
                created_at: "created_at",
                favorited_at: "favorited_at",
                asset: {
                    type: "generated_audio",
                    duration_ms: 1,
                    url: "url",
                    generated_audio_inputs: { text_prompt: "text_prompt" },
                    transcriptions: [{ key: "value" }],
                },
            },
        ];

        server.mockEndpoint().get("/voices").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.listVoices();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_assets (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                id: "id",
                type: "text",
                name: "name",
                thumbnail_url: "thumbnail_url",
                description: "description",
                is_favorite: true,
                recent: true,
                created_at: "created_at",
                favorited_at: "favorited_at",
                asset: {
                    type: "generated_audio",
                    duration_ms: 1,
                    url: "url",
                    generated_audio_inputs: { text_prompt: "text_prompt" },
                    transcriptions: [{ key: "value" }],
                },
            },
        ];

        server.mockEndpoint().get("/assets").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.listAssets({
            type: "text",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list_assets (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/assets").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.listAssets({
                type: "text",
            });
        }).rejects.toThrow(Hedra.UnprocessableEntityError);
    });

    test("create_asset (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", type: "text" };
        const rawResponseBody = { name: "name", type: "text", id: "id", upload_url: "upload_url" };

        server
            .mockEndpoint()
            .post("/assets")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.createAsset({
            name: "name",
            type: "text",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create_asset (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", type: "text" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/assets")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.createAsset({
                name: "name",
                type: "text",
            });
        }).rejects.toThrow(Hedra.UnprocessableEntityError);
    });

    test("list_generations (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            page_info: { limit: 1, offset: 1 },
            data: [
                {
                    id: "id",
                    type: "text",
                    input: {
                        type: "audio_from_video",
                        audio_generation_model_id: "audio_generation_model_id",
                        video_id: "video_id",
                    },
                    status: "complete",
                    progress: 1.1,
                    eta_sec: 1,
                    created_at: "created_at",
                    credit_cost: 1,
                    batch_generation_id: "batch_generation_id",
                    asset: {
                        id: "id",
                        type: "text",
                        name: "name",
                        thumbnail_url: "thumbnail_url",
                        created_at: "created_at",
                        asset: {
                            type: "generated_audio",
                            duration_ms: 1,
                            url: "url",
                            generated_audio_inputs: { text_prompt: "text_prompt" },
                        },
                    },
                    error: { type: "UNKNOWN", message: "message" },
                    error_message: "error_message",
                },
            ],
        };

        server.mockEndpoint().get("/generations").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.listGenerations();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_generations (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/generations").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.listGenerations();
        }).rejects.toThrow(Hedra.UnprocessableEntityError);
    });

    test("generate_asset (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "video", generated_video_inputs: { text_prompt: "text_prompt" } };
        const rawResponseBody = {
            type: "video",
            workspace_id: "workspace_id",
            agent_thread_id: "agent_thread_id",
            generation_id: "generation_id",
            generation_ids: ["generation_ids"],
            ai_model_id: "ai_model_id",
            start_keyframe_id: "start_keyframe_id",
            start_keyframe_url: "start_keyframe_url",
            end_keyframe_id: "end_keyframe_id",
            end_keyframe_url: "end_keyframe_url",
            audio_id: "audio_id",
            audio_generation: {
                workspace_id: "workspace_id",
                agent_thread_id: "agent_thread_id",
                generation_id: "generation_id",
                generation_ids: ["generation_ids"],
                type: "text_to_speech",
                voice_id: "voice_id",
                model_id: "model_id",
                text: "text",
                stability: 1.1,
                speed: 1.1,
                language: "Chinese",
            },
            audio_start_ms: 1,
            reference_image_ids: ["reference_image_ids"],
            video_id: "video_id",
            generated_video_inputs: {
                text_prompt: "text_prompt",
                ai_model_id: "ai_model_id",
                resolution: "resolution",
                aspect_ratio: "aspect_ratio",
                duration_ms: 1,
                bounding_box_target: [{ key: "value" }],
                character_orientation: "video",
                enhance_prompt: true,
            },
            batch_size: 1,
            id: "id",
            asset_id: "asset_id",
            created_at: "created_at",
            status: "complete",
            progress: 1.1,
            eta_sec: 1,
            batch_generation_id: "batch_generation_id",
            batch_results: [
                {
                    id: "id",
                    asset_id: "asset_id",
                    created_at: "created_at",
                    status: "complete",
                    progress: 1.1,
                    error: "error",
                },
            ],
        };

        server
            .mockEndpoint()
            .post("/generations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.generateAsset({
            type: "video",
            generated_video_inputs: {
                text_prompt: "text_prompt",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("generate_asset (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "video", generated_video_inputs: { text_prompt: "text_prompt" } };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/generations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.generateAsset({
                type: "video",
                generated_video_inputs: {
                    text_prompt: "text_prompt",
                },
            });
        }).rejects.toThrow(Hedra.UnprocessableEntityError);
    });

    test("get_status (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            asset_id: "asset_id",
            type: "text",
            status: "complete",
            progress: 1.1,
            created_at: "created_at",
            error_message: "error_message",
            url: "url",
            download_url: "download_url",
            streaming_url: "streaming_url",
            workspace_id: "workspace_id",
        };

        server
            .mockEndpoint()
            .get("/generations/generation_id/status")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.getStatus({
            generation_id: "generation_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_status (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/generations/generation_id/status")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.getStatus({
                generation_id: "generation_id",
            });
        }).rejects.toThrow(Hedra.UnprocessableEntityError);
    });

    test("get_credits", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { remaining: 1, expiring: 1, used: 1, workspace_credits: { key: 1 } };

        server.mockEndpoint().get("/billing/credits").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.getCredits();
        expect(response).toEqual(rawResponseBody);
    });
});
