// This file was auto-generated by Fern from our API Definition.

import * as Hedra from "../../src/api/index";
import { HedraClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ModelsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: "id",
                    modality: "modality",
                    name: "name",
                    description: "description",
                    thumbnail_url: "thumbnail_url",
                    premium: true,
                },
            ],
            next_cursor: "next_cursor",
        };

        server.mockEndpoint().get("/models").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.models.list();
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/models").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.models.list();
        }).rejects.toThrow(Hedra.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/models").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.models.list();
        }).rejects.toThrow(Hedra.ForbiddenError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/models").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.models.list();
        }).rejects.toThrow(Hedra.NotFoundError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/models").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.models.list();
        }).rejects.toThrow(Hedra.UnprocessableEntityError);
    });

    test("list (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/models").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.models.list();
        }).rejects.toThrow(Hedra.TooManyRequestsError);
    });

    test("list (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/models").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.models.list();
        }).rejects.toThrow(Hedra.InternalServerError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            kind: "kind",
            modality: "modality",
            name: "name",
            description: "description",
            input_schema: { key: "value" },
            output_schema: { key: "value" },
            routing: [{ when: "when", variant: "variant" }],
            variants: [{ id: "id", mode: "mode", input_schema: { key: "value" }, output_schema: { key: "value" } }],
        };

        server.mockEndpoint().get("/models/model").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.models.get("model");
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/models/model").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.models.get("model");
        }).rejects.toThrow(Hedra.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/models/model").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.models.get("model");
        }).rejects.toThrow(Hedra.ForbiddenError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/models/model").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.models.get("model");
        }).rejects.toThrow(Hedra.NotFoundError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/models/model").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.models.get("model");
        }).rejects.toThrow(Hedra.UnprocessableEntityError);
    });

    test("get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/models/model").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.models.get("model");
        }).rejects.toThrow(Hedra.TooManyRequestsError);
    });

    test("get (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server.mockEndpoint().get("/models/model").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.models.get("model");
        }).rejects.toThrow(Hedra.InternalServerError);
    });

    test("list_voices (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [{ id: "id", name: "name", preview_url: "preview_url", labels: { key: "value" } }],
            next_cursor: "next_cursor",
        };

        server
            .mockEndpoint()
            .get("/models/model/voices")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.models.listVoices("model");
        expect(response).toEqual(rawResponseBody);
    });

    test("list_voices (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .get("/models/model/voices")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.models.listVoices("model");
        }).rejects.toThrow(Hedra.BadRequestError);
    });

    test("list_voices (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .get("/models/model/voices")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.models.listVoices("model");
        }).rejects.toThrow(Hedra.ForbiddenError);
    });

    test("list_voices (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .get("/models/model/voices")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.models.listVoices("model");
        }).rejects.toThrow(Hedra.NotFoundError);
    });

    test("list_voices (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/models/model/voices")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.models.listVoices("model");
        }).rejects.toThrow(Hedra.UnprocessableEntityError);
    });

    test("list_voices (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .get("/models/model/voices")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.models.listVoices("model");
        }).rejects.toThrow(Hedra.TooManyRequestsError);
    });

    test("list_voices (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .get("/models/model/voices")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.models.listVoices("model");
        }).rejects.toThrow(Hedra.InternalServerError);
    });

    test("get_openapi (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/models/model/openapi.json")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.models.getOpenapi("model");
        expect(response).toEqual(rawResponseBody);
    });

    test("get_openapi (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .get("/models/model/openapi.json")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.models.getOpenapi("model");
        }).rejects.toThrow(Hedra.BadRequestError);
    });

    test("get_openapi (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .get("/models/model/openapi.json")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.models.getOpenapi("model");
        }).rejects.toThrow(Hedra.ForbiddenError);
    });

    test("get_openapi (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .get("/models/model/openapi.json")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.models.getOpenapi("model");
        }).rejects.toThrow(Hedra.NotFoundError);
    });

    test("get_openapi (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/models/model/openapi.json")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.models.getOpenapi("model");
        }).rejects.toThrow(Hedra.UnprocessableEntityError);
    });

    test("get_openapi (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .get("/models/model/openapi.json")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.models.getOpenapi("model");
        }).rejects.toThrow(Hedra.TooManyRequestsError);
    });

    test("get_openapi (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .get("/models/model/openapi.json")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.models.getOpenapi("model");
        }).rejects.toThrow(Hedra.InternalServerError);
    });

    test("estimate (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { model: "model", credits: 1 };

        server
            .mockEndpoint()
            .post("/models/model/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.models.estimate("model");
        expect(response).toEqual(rawResponseBody);
    });

    test("estimate (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .post("/models/model/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.models.estimate("model");
        }).rejects.toThrow(Hedra.BadRequestError);
    });

    test("estimate (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .post("/models/model/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.models.estimate("model");
        }).rejects.toThrow(Hedra.UnauthorizedError);
    });

    test("estimate (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .post("/models/model/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.models.estimate("model");
        }).rejects.toThrow(Hedra.ForbiddenError);
    });

    test("estimate (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .post("/models/model/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.models.estimate("model");
        }).rejects.toThrow(Hedra.NotFoundError);
    });

    test("estimate (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/models/model/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.models.estimate("model");
        }).rejects.toThrow(Hedra.UnprocessableEntityError);
    });

    test("estimate (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .post("/models/model/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.models.estimate("model");
        }).rejects.toThrow(Hedra.TooManyRequestsError);
    });

    test("estimate (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .post("/models/model/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.models.estimate("model");
        }).rejects.toThrow(Hedra.InternalServerError);
    });
});
