// This file was auto-generated by Fern from our API Definition.

import * as Hedra from "../../src/api/index";
import { HedraClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("QueueClient", () => {
    test("submit (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            request_id: "request_id",
            model: "model",
            status: "IN_QUEUE",
            status_url: "status_url",
            response_url: "response_url",
            estimated_completion_at: "estimated_completion_at",
        };

        server
            .mockEndpoint()
            .post("/queue/model")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.queue.submit("model");
        expect(response).toEqual(rawResponseBody);
    });

    test("submit (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .post("/queue/model")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.queue.submit("model");
        }).rejects.toThrow(Hedra.BadRequestError);
    });

    test("submit (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .post("/queue/model")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.queue.submit("model");
        }).rejects.toThrow(Hedra.UnauthorizedError);
    });

    test("submit (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .post("/queue/model")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.queue.submit("model");
        }).rejects.toThrow(Hedra.ForbiddenError);
    });

    test("submit (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .post("/queue/model")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.queue.submit("model");
        }).rejects.toThrow(Hedra.NotFoundError);
    });

    test("submit (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/queue/model")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.queue.submit("model");
        }).rejects.toThrow(Hedra.UnprocessableEntityError);
    });

    test("submit (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .post("/queue/model")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.queue.submit("model");
        }).rejects.toThrow(Hedra.TooManyRequestsError);
    });

    test("submit (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new HedraClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "UNKNOWN", message: "message" } };

        server
            .mockEndpoint()
            .post("/queue/model")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.queue.submit("model");
        }).rejects.toThrow(Hedra.InternalServerError);
    });
});
