// This file was auto-generated by Fern from our API Definition.

import { BillingClient } from "./api/resources/billing/client/Client.js";
import { ChatClient } from "./api/resources/chat/client/Client.js";
import { FilesClient } from "./api/resources/files/client/Client.js";
import { JobsClient } from "./api/resources/jobs/client/Client.js";
import { KeysClient } from "./api/resources/keys/client/Client.js";
import { LogDrainsClient } from "./api/resources/logDrains/client/Client.js";
import { ModelsClient } from "./api/resources/models/client/Client.js";
import { TokensClient } from "./api/resources/tokens/client/Client.js";
import { WebhooksClient } from "./api/resources/webhooks/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace HedraClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class HedraClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<HedraClient.Options>;
    protected _jobs: JobsClient | undefined;
    protected _models: ModelsClient | undefined;
    protected _keys: KeysClient | undefined;
    protected _tokens: TokensClient | undefined;
    protected _files: FilesClient | undefined;
    protected _billing: BillingClient | undefined;
    protected _webhooks: WebhooksClient | undefined;
    protected _logDrains: LogDrainsClient | undefined;
    protected _chat: ChatClient | undefined;

    constructor(options: HedraClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get jobs(): JobsClient {
        return (this._jobs ??= new JobsClient(this._options));
    }

    public get models(): ModelsClient {
        return (this._models ??= new ModelsClient(this._options));
    }

    public get keys(): KeysClient {
        return (this._keys ??= new KeysClient(this._options));
    }

    public get tokens(): TokensClient {
        return (this._tokens ??= new TokensClient(this._options));
    }

    public get files(): FilesClient {
        return (this._files ??= new FilesClient(this._options));
    }

    public get billing(): BillingClient {
        return (this._billing ??= new BillingClient(this._options));
    }

    public get webhooks(): WebhooksClient {
        return (this._webhooks ??= new WebhooksClient(this._options));
    }

    public get logDrains(): LogDrainsClient {
        return (this._logDrains ??= new LogDrainsClient(this._options));
    }

    public get chat(): ChatClient {
        return (this._chat ??= new ChatClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
