// This file was auto-generated by Fern from our API Definition.

export const HedraEnvironment = {
    Production: "https://api.hedra.com/v3",
} as const;

export type HedraEnvironment = typeof HedraEnvironment.Production;
