// This file was auto-generated by Fern from our API Definition.

import type * as Hedra from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface TokenCreateRequest {
    ttl_seconds?: number | null;
    scopes?: Hedra.ApiKeyScope[] | null;
}
