// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Hedra from "../../../index.js";

export declare namespace RequestsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Poll, stream, and list submitted requests.
 */
export class RequestsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<RequestsClient.Options>;

    constructor(options: RequestsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {Hedra.ListRequestsRequest} request
     * @param {RequestsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Hedra.BadRequestError}
     * @throws {@link Hedra.UnauthorizedError}
     * @throws {@link Hedra.ForbiddenError}
     * @throws {@link Hedra.NotFoundError}
     * @throws {@link Hedra.UnprocessableEntityError}
     * @throws {@link Hedra.TooManyRequestsError}
     * @throws {@link Hedra.InternalServerError}
     *
     * @example
     *     await client.requests.list()
     */
    public async list(
        request: Hedra.ListRequestsRequest = {},
        requestOptions?: RequestsClient.RequestOptions,
    ): Promise<core.Page<Hedra.RequestSummary, Hedra.RequestListResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (request: Hedra.ListRequestsRequest): Promise<core.WithRawResponse<Hedra.RequestListResponse>> => {
                const { limit, cursor } = request;
                const _queryParams: Record<string, unknown> = {
                    limit,
                    cursor,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await core.fetcher({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.HedraEnvironment.Production,
                        "requests",
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return { data: _response.body as Hedra.RequestListResponse, rawResponse: _response.rawResponse };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new Hedra.BadRequestError(
                                _response.error.body as Hedra.ErrorResponse,
                                _response.rawResponse,
                            );
                        case 401:
                            throw new Hedra.UnauthorizedError(
                                _response.error.body as Hedra.ErrorResponse,
                                _response.rawResponse,
                            );
                        case 403:
                            throw new Hedra.ForbiddenError(
                                _response.error.body as Hedra.ErrorResponse,
                                _response.rawResponse,
                            );
                        case 404:
                            throw new Hedra.NotFoundError(
                                _response.error.body as Hedra.ErrorResponse,
                                _response.rawResponse,
                            );
                        case 422:
                            throw new Hedra.UnprocessableEntityError(
                                _response.error.body as Hedra.HttpValidationError,
                                _response.rawResponse,
                            );
                        case 429:
                            throw new Hedra.TooManyRequestsError(
                                _response.error.body as Hedra.ErrorResponse,
                                _response.rawResponse,
                            );
                        case 500:
                            throw new Hedra.InternalServerError(
                                _response.error.body as Hedra.ErrorResponse,
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.HedraError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/requests");
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<Hedra.RequestSummary, Hedra.RequestListResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.next_cursor != null &&
                !(typeof response?.next_cursor === "string" && response?.next_cursor === ""),
            getItems: (response) => response?.data ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "cursor", response?.next_cursor));
            },
        });
    }

    /**
     * @param {string} request_id
     * @param {Hedra.GetRequestsRequest} request
     * @param {RequestsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Hedra.BadRequestError}
     * @throws {@link Hedra.UnauthorizedError}
     * @throws {@link Hedra.ForbiddenError}
     * @throws {@link Hedra.NotFoundError}
     * @throws {@link Hedra.UnprocessableEntityError}
     * @throws {@link Hedra.TooManyRequestsError}
     * @throws {@link Hedra.InternalServerError}
     *
     * @example
     *     await client.requests.get("request_id")
     */
    public get(
        request_id: string,
        request: Hedra.GetRequestsRequest = {},
        requestOptions?: RequestsClient.RequestOptions,
    ): core.HttpResponsePromise<Hedra.ResultResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(request_id, request, requestOptions));
    }

    private async __get(
        request_id: string,
        _request: Hedra.GetRequestsRequest = {},
        requestOptions?: RequestsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Hedra.ResultResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.HedraEnvironment.Production,
                `requests/${core.url.encodePathParam(request_id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Hedra.ResultResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Hedra.BadRequestError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 401:
                    throw new Hedra.UnauthorizedError(
                        _response.error.body as Hedra.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Hedra.ForbiddenError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 404:
                    throw new Hedra.NotFoundError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Hedra.UnprocessableEntityError(
                        _response.error.body as Hedra.HttpValidationError,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Hedra.TooManyRequestsError(
                        _response.error.body as Hedra.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Hedra.InternalServerError(
                        _response.error.body as Hedra.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.HedraError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/requests/{request_id}");
    }

    /**
     * @param {string} request_id
     * @param {Hedra.GetStatusRequestsRequest} request
     * @param {RequestsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Hedra.BadRequestError}
     * @throws {@link Hedra.UnauthorizedError}
     * @throws {@link Hedra.ForbiddenError}
     * @throws {@link Hedra.NotFoundError}
     * @throws {@link Hedra.UnprocessableEntityError}
     * @throws {@link Hedra.TooManyRequestsError}
     * @throws {@link Hedra.InternalServerError}
     *
     * @example
     *     await client.requests.getStatus("request_id")
     */
    public getStatus(
        request_id: string,
        request: Hedra.GetStatusRequestsRequest = {},
        requestOptions?: RequestsClient.RequestOptions,
    ): core.HttpResponsePromise<Hedra.StatusResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getStatus(request_id, request, requestOptions));
    }

    private async __getStatus(
        request_id: string,
        _request: Hedra.GetStatusRequestsRequest = {},
        requestOptions?: RequestsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Hedra.StatusResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.HedraEnvironment.Production,
                `requests/${core.url.encodePathParam(request_id)}/status`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Hedra.StatusResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Hedra.BadRequestError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 401:
                    throw new Hedra.UnauthorizedError(
                        _response.error.body as Hedra.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Hedra.ForbiddenError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 404:
                    throw new Hedra.NotFoundError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Hedra.UnprocessableEntityError(
                        _response.error.body as Hedra.HttpValidationError,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Hedra.TooManyRequestsError(
                        _response.error.body as Hedra.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Hedra.InternalServerError(
                        _response.error.body as Hedra.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.HedraError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/requests/{request_id}/status");
    }

    /**
     * @param {string} request_id
     * @param {Hedra.StreamRequestsRequest} request
     * @param {RequestsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Hedra.BadRequestError}
     * @throws {@link Hedra.UnauthorizedError}
     * @throws {@link Hedra.ForbiddenError}
     * @throws {@link Hedra.NotFoundError}
     * @throws {@link Hedra.UnprocessableEntityError}
     * @throws {@link Hedra.TooManyRequestsError}
     * @throws {@link Hedra.InternalServerError}
     *
     * @example
     *     await client.requests.stream("request_id")
     */
    public stream(
        request_id: string,
        request: Hedra.StreamRequestsRequest = {},
        requestOptions?: RequestsClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__stream(request_id, request, requestOptions));
    }

    private async __stream(
        request_id: string,
        request: Hedra.StreamRequestsRequest = {},
        requestOptions?: RequestsClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { "Last-Event-Id": lastEventId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Last-Event-Id": lastEventId ?? undefined }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.HedraEnvironment.Production,
                `requests/${core.url.encodePathParam(request_id)}/stream`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Hedra.BadRequestError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 401:
                    throw new Hedra.UnauthorizedError(
                        _response.error.body as Hedra.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Hedra.ForbiddenError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 404:
                    throw new Hedra.NotFoundError(_response.error.body as Hedra.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Hedra.UnprocessableEntityError(
                        _response.error.body as Hedra.HttpValidationError,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Hedra.TooManyRequestsError(
                        _response.error.body as Hedra.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Hedra.InternalServerError(
                        _response.error.body as Hedra.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.HedraError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/requests/{request_id}/stream");
    }
}
